### ISSUE TITLE
Multithreading not working - how to diagnose? 

### ISSUE THREAD

**Issue by pdcountway** [RcppCore/RcppParallel#103]
Hi - We have been having problems implementing an R package (dada2) that relies on RcppParallel on our HPC (180 cores, 1.25 TB RAM). We're running the latest versions of both R (3.6.2) and dada2 (v.1.14.0) and using PBS Pro to submit jobs. It appears that specific steps in dada2 which utilize multithreading via RcppParallel are failing. We recognize that this is likely a problem specific to our installation (or network architecture?) but could use some advice on how to get this working properly. Relevant discussion over on the dada2 Github page is linked below: 
https://github.com/benjjneb/dada2/issues/926#issuecomment-582472391
@benjjneb @kguay @btupper
Thanks,
Pete

**Comment by kevinushey** [comment]
Without being able to see your source code and how you're using RcppParallel, it's hard to say. The documentation on tuning + thread options may be relevant:

https://rcppcore.github.io/RcppParallel/#tuning

You might also want to confirm that:

```
parallel::detectCores()
RcppParallel::defaultNumThreads()
```

is reporting the number of cores (threads) you expect to see.

**Comment by pdcountway** [comment]
Thanks very much for your reply Kevin - I'm waiting for our system administrator to review your suggestions as I don't have access to this information. Cheers, Pete

**Comment by kguay** [comment]
> Without being able to see your source code and how you're using RcppParallel, it's hard to say. The documentation on tuning + thread options may be relevant:
> 
> https://rcppcore.github.io/RcppParallel/#tuning
> 
> You might also want to confirm that:
> 
> ```
> parallel::detectCores()
> RcppParallel::defaultNumThreads()
> ```
> 
> is reporting the number of cores (threads) you expect to see.

Rcppparallel sees all of the cores on the HPC, regardless of what you request with PBS Pro.  I have tried specifying the number of threads using the RcppParallel function, but that doesn't help. It doesn't make sense to me that multithreading works with filterAndTrim, but not learnErrors..

**Comment by kguay** [comment]
Hi @kevinushey,

I just tried doing a local dada2 install on my Mac and running through the tutorial. I got the same results as on our HPC: the filterAndTrim step spins up multiple threads, but the other steps (e.g. learnErrors) does not. Can you please confirm that you see multithread activity (multiple instances of R running) when running learnErrors?

Thank you,
Kevin

**Comment by pdcountway** [comment]
Multithreading via RcppParellel now seems to be running for the current application (dada2). It's unclear what was causing the behavior that we reported previously. The only difference with the current process is that we did not submit the job via PBS Pro.
