### ISSUE TITLE
Enable building with the system tbb library

### ISSUE THREAD

**Issue by bryteise** [RcppCore/RcppParallel#107]
I'd like to build against the system tbb instead of the embedded tbb provided by the source package. Looking at the build process this seems like a bigger patch though. Would that be something you would consider adding?

**Comment by eddelbuettel** [comment]
Tough. In general, we can support this -- I once enabled just that for [nloptr](https://cloud.r-project.org/web/packages/nloptr/index.html).

But this is a much larger and complicated package so I am not sure.  Call to be made by @kevinushey.

**Comment by kevinushey** [comment]
Seems possible in theory. We load TBB when RcppParallel is loaded here:

https://github.com/RcppCore/RcppParallel/blob/b216ba27dcbd3c523932bd918b6dd0b1b08d3566/R/hooks.R#L7-L23

We'd just have to swap out those paths for something separately provided / requested by the user.

However, I'm not sure if TBB is intended to be used in this way, or if things could subtly break.

**Comment by bryteise** [comment]
I patched tbbLibPath to just return the path to the system installed libtbb as a workaround to avoid shipping the vendored libtbb. Currently my project's opencv is linking against the system libtbb without issue. Things often are a little trickier when dlopening though as RccpParallel does since you won't see library version mismatches at build time.

**Comment by eddelbuettel** [comment]
Keep at it.  This will be worthwhile.

**Comment by dsteuer** [comment]
Hunting for a solution of a different issue I came around the debian patch for using the system tbb.
https://salsa.debian.org/r-pkg-team/r-cran-rcppparallel/-/blob/master/debian/patches/use_debian_packaged_libtbb.patch

Would you advise against using of the system's tbb?  Otherwise I would build for OpenSUSE just like debian does.

**Comment by eddelbuettel** [comment]
It is not my package, hence not my call.  _In general_,  I like using system libs, but there is a risk of a delta.

**Comment by kevinushey** [comment]
I wouldn't advise against it, I just haven't tested it yet. I'd like to eventually do this properly but haven't yet been able to carve out the time to do it (but would gladly accept a PR)
