### ISSUE TITLE
Performance of RcppParallel for different numThreads

### ISSUE THREAD

**Issue by WenjianBI** [RcppCore/RcppParallel#109]
I am developing a tool in which the RcppParallel is important to increase computational efficiency. However, I found when I set a large numThreads, RcppParallel would not increase efficiency any more. The below is an example from https://gallery.rcpp.org/articles/parallel-vector-sum/, and I set different numThreads. It seems that improvement of RcppParallel is limited and would not increase as the increase of numThreads. My question is 1) Is it expected that RcppParallel can only reduce computation time by 1/2 no matter how many numThreads is used; 2) Is there any other options to fully use multiple CPU cores in Rcpp/RcppArmadillo?  

```r
> RcppParallel::defaultNumThreads()
[1] 24
> RcppParallel::setThreadOptions(numThreads = 1)
> res <- benchmark(vectorSum(v), parallelVectorSum(v), order="relative", replications = 10)
> res[,1:4]
test replications elapsed relative
1         vectorSum(v)           10   1.352    1.000
2 parallelVectorSum(v)           10   1.378    1.019
> 
> RcppParallel::setThreadOptions(numThreads = 2)
> res <- benchmark(vectorSum(v), parallelVectorSum(v), order="relative", replications = 10)
> res[,1:4]
test replications elapsed relative
2 parallelVectorSum(v)           10   0.670    1.000
1         vectorSum(v)           10   1.117    1.667
> 
> RcppParallel::setThreadOptions(numThreads = 4)
> res <- benchmark(vectorSum(v), parallelVectorSum(v), order="relative", replications = 10)
> res[,1:4]
test replications elapsed relative
2 parallelVectorSum(v)           10   0.559    1.000
1         vectorSum(v)           10   1.091    1.952
> 
> RcppParallel::setThreadOptions(numThreads = 24)
> res <- benchmark(vectorSum(v), parallelVectorSum(v), order="relative", replications = 10)
> res[,1:4]
test replications elapsed relative
2 parallelVectorSum(v)           10   0.552    1.000
1         vectorSum(v)           10   1.086    1.967
```

**Comment by eddelbuettel** [comment]
"It's complicated."  There are many issues involved.

Also note that you _can_ get multithreading "for free" via OpenBLAS and to some extend within (Rcpp)Armadillo though it will only cover some operations.

**Comment by WenjianBI** [comment]
Thank you for the swift reply.
