### ISSUE TITLE
Build error on R 3.6.3, Mac OS 10.15.3.

### ISSUE THREAD

**Issue by anirban-mukherjee** [RcppCore/RcppParallel#112]
I get a build failure when trying to install RcppParallel from source. I get the same error when installing from GitHub (using devtools::install_github) and from CRAN. Below is the system and session information and then the console output. 

General system info:

OS: Mac OS 10.15.3. 
C Compiler: Apple clang version 11.0.0 (clang-1100.0.33.17)
Fortran Compiler: ifort version 19.1.0.166
R: R 3.6.3 (r77957).

--

Session info:

R version 3.6.3 Patched (2020-01-18 r77957)
Platform: x86_64-apple-darwin19.3.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] C/UTF-8/C/C/C/C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3

--

Build error:

Installing package into ‘/Users/anirbanmukherjee/Library/R/3.6/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘RcppParallel’ ...
** using staged installation
** preparing to configure package 'RcppParallel' ...
*** executing 'R CMD config'
*** configured file: 'src/Makevars.in' => 'src/Makevars'
** finished configure for package 'RcppParallel'
** libs
mkdir -p ../inst/lib/; \
	cd tbb/src; \
	if [ -n "clang" ]; then \
	   CONLY="clang -I/usr/local/include" CPLUS="clang++ -I/usr/local/include" CXXFLAGS="-march=native -O3 -DTBB_NO_LEGACY=1" PIC_KEY="-fPIC" WARNING_SUPPRESS="" make -e -s stdver=c++0x compiler=clang tbb_release tbbmalloc_release tbb_build_prefix=lib; \
	elif [ -n "" ]; then \
	   CONLY="clang -I/usr/local/include" CPLUS="clang++ -I/usr/local/include" CXXFLAGS="-march=native -O3 -DTBB_NO_LEGACY=1" PIC_KEY="-fPIC" WARNING_SUPPRESS="" make -e -s stdver=c++0x compiler=gcc tbb_release tbbmalloc_release tbb_build_prefix=lib; \
	else \
	   CONLY="clang -I/usr/local/include" CPLUS="clang++ -I/usr/local/include" CXXFLAGS="-march=native -O3 -DTBB_NO_LEGACY=1" PIC_KEY="-fPIC" WARNING_SUPPRESS="" make -e -s stdver=c++0x tbb_release tbbmalloc_release tbb_build_prefix=lib; \
	fi; \
	cd ../..; \
	cp tbb/build/lib_release/libtbb*.* ../inst/lib/
Created ../build/lib_release directory
../../build/Makefile.tbb:32: CONFIG: cfg=release arch=intel64 compiler=clang target=macos runtime=cc11.0.0_os10.15.3
In file included from ../../src/tbb/concurrent_queue.cpp:26:
In file included from /usr/local/include/tbb/internal/_concurrent_queue_impl.h:26:
/usr/local/include/tbb/internal/../atomic.h:21:9: warning: TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features
      appendix in the TBB reference manual. [-W#pragma-messages]
#pragma message("TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
        ^
In file included from ../../src/tbb/concurrent_queue.cpp:27:
In file included from ../../src/tbb/concurrent_monitor.h:28:
/usr/local/include/tbb/aligned_space.h:21:9: warning: TBB Warning: tbb/aligned_space.h is deprecated. For details, please see Deprecated
      Features appendix in the TBB reference manual. [-W#pragma-messages]
#pragma message("TBB Warning: tbb/aligned_space.h is deprecated. For details, please see Deprecated Features appendix in the TBB refere...
        ^
2 warnings generated.
In file included from ../../src/tbb/concurrent_vector.cpp:30:
In file included from ../../src/tbb/tbb_misc.h:26:
/usr/local/include/tbb/atomic.h:21:9: warning: TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in
      the TBB reference manual. [-W#pragma-messages]
#pragma message("TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
        ^
1 warning generated.
In file included from ../../src/tbb/dynamic_link.cpp:57:
In file included from ../../src/tbb/tbb_misc.h:26:
/usr/local/include/tbb/atomic.h:21:9: warning: TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in
      the TBB reference manual. [-W#pragma-messages]
#pragma message("TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
        ^
1 warning generated.
In file included from ../../src/tbb/cache_aligned_allocator.cpp:25:
In file included from ../../src/tbb/tbb_misc.h:26:
/usr/local/include/tbb/atomic.h:21:9: warning: TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in
      the TBB reference manual. [-W#pragma-messages]
#pragma message("TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
        ^
1 warning generated.
../../src/tbb/pipeline.cpp:57:23: warning: 'pipeline' is deprecated: tbb::pipeline is deprecated, use tbb::parallel_pipeline
      [-Wdeprecated-declarations]
    friend class tbb::pipeline;
                      ^
/usr/local/include/tbb/pipeline.h:235:7: note: 'pipeline' has been explicitly marked deprecated here
class __TBB_DEPRECATED_MSG("tbb::pipeline is deprecated, use tbb::parallel_pipeline") pipeline {
      ^
/usr/local/include/tbb/tbb_config.h:631:58: note: expanded from macro '__TBB_DEPRECATED_MSG'
        #define __TBB_DEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
                                                         ^
../../src/tbb/pipeline.cpp:255:23: warning: 'pipeline' is deprecated: tbb::pipeline is deprecated, use tbb::parallel_pipeline
      [-Wdeprecated-declarations]
    friend class tbb::pipeline;
                      ^
/usr/local/include/tbb/pipeline.h:235:7: note: 'pipeline' has been explicitly marked deprecated here
class __TBB_DEPRECATED_MSG("tbb::pipeline is deprecated, use tbb::parallel_pipeline") pipeline {
      ^
/usr/local/include/tbb/tbb_config.h:631:58: note: expanded from macro '__TBB_DEPRECATED_MSG'
        #define __TBB_DEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
                                                         ^
../../src/tbb/pipeline.cpp:256:5: warning: 'pipeline' is deprecated: tbb::pipeline is deprecated, use tbb::parallel_pipeline
      [-Wdeprecated-declarations]
    pipeline& my_pipeline;
    ^
/usr/local/include/tbb/pipeline.h:235:7: note: 'pipeline' has been explicitly marked deprecated here
class __TBB_DEPRECATED_MSG("tbb::pipeline is deprecated, use tbb::parallel_pipeline") pipeline {
      ^
/usr/local/include/tbb/tbb_config.h:631:58: note: expanded from macro '__TBB_DEPRECATED_MSG'
        #define __TBB_DEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
                                                         ^
../../src/tbb/pipeline.cpp:264:17: warning: 'pipeline' is deprecated: tbb::pipeline is deprecated, use tbb::parallel_pipeline
      [-Wdeprecated-declarations]
    stage_task( pipeline& pipeline ) :
                ^
/usr/local/include/tbb/pipeline.h:235:7: note: 'pipeline' has been explicitly marked deprecated here
class __TBB_DEPRECATED_MSG("tbb::pipeline is deprecated, use tbb::parallel_pipeline") pipeline {
      ^
/usr/local/include/tbb/tbb_config.h:631:58: note: expanded from macro '__TBB_DEPRECATED_MSG'
        #define __TBB_DEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
                                                         ^
../../src/tbb/pipeline.cpp:272:17: warning: 'pipeline' is deprecated: tbb::pipeline is deprecated, use tbb::parallel_pipeline
      [-Wdeprecated-declarations]
    stage_task( pipeline& pipeline, filter* filter_, const task_info& info ) :
                ^
/usr/local/include/tbb/pipeline.h:235:7: note: 'pipeline' has been explicitly marked deprecated here
class __TBB_DEPRECATED_MSG("tbb::pipeline is deprecated, use tbb::parallel_pipeline") pipeline {
      ^
/usr/local/include/tbb/tbb_config.h:631:58: note: expanded from macro '__TBB_DEPRECATED_MSG'
        #define __TBB_DEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
                                                         ^
../../src/tbb/pipeline.cpp:405:5: warning: 'pipeline' is deprecated: tbb::pipeline is deprecated, use tbb::parallel_pipeline
      [-Wdeprecated-declarations]
    pipeline& my_pipeline;
    ^
/usr/local/include/tbb/pipeline.h:235:7: note: 'pipeline' has been explicitly marked deprecated here
class __TBB_DEPRECATED_MSG("tbb::pipeline is deprecated, use tbb::parallel_pipeline") pipeline {
      ^
/usr/local/include/tbb/tbb_config.h:631:58: note: expanded from macro '__TBB_DEPRECATED_MSG'
        #define __TBB_DEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
                                                         ^
../../src/tbb/pipeline.cpp:459:25: warning: 'pipeline' is deprecated: tbb::pipeline is deprecated, use tbb::parallel_pipeline
      [-Wdeprecated-declarations]
    pipeline_root_task( pipeline& pipeline ): my_pipeline(pipeline), do_segment_scanning(false)
                        ^
/usr/local/include/tbb/pipeline.h:235:7: note: 'pipeline' has been explicitly marked deprecated here
class __TBB_DEPRECATED_MSG("tbb::pipeline is deprecated, use tbb::parallel_pipeline") pipeline {
      ^
/usr/local/include/tbb/tbb_config.h:631:58: note: expanded from macro '__TBB_DEPRECATED_MSG'
        #define __TBB_DEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
                                                         ^
../../src/tbb/pipeline.cpp:488:5: warning: 'pipeline' is deprecated: tbb::pipeline is deprecated, use tbb::parallel_pipeline
      [-Wdeprecated-declarations]
    pipeline& my_pipeline;
    ^
/usr/local/include/tbb/pipeline.h:235:7: note: 'pipeline' has been explicitly marked deprecated here
class __TBB_DEPRECATED_MSG("tbb::pipeline is deprecated, use tbb::parallel_pipeline") pipeline {
      ^
/usr/local/include/tbb/tbb_config.h:631:58: note: expanded from macro '__TBB_DEPRECATED_MSG'
        #define __TBB_DEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
                                                         ^
../../src/tbb/pipeline.cpp:490:22: warning: 'pipeline' is deprecated: tbb::pipeline is deprecated, use tbb::parallel_pipeline
      [-Wdeprecated-declarations]
    pipeline_cleaner(pipeline& _pipeline) :
                     ^
/usr/local/include/tbb/pipeline.h:235:7: note: 'pipeline' has been explicitly marked deprecated here
class __TBB_DEPRECATED_MSG("tbb::pipeline is deprecated, use tbb::parallel_pipeline") pipeline {
      ^
/usr/local/include/tbb/tbb_config.h:631:58: note: expanded from macro '__TBB_DEPRECATED_MSG'
        #define __TBB_DEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
                                                         ^
9 warnings generated.
In file included from ../../src/tbb/queuing_mutex.cpp:24:
In file included from ../../src/tbb/tbb_misc.h:26:
/usr/local/include/tbb/atomic.h:21:9: warning: TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in
      the TBB reference manual. [-W#pragma-messages]
#pragma message("TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
        ^
1 warning generated.
In file included from ../../src/tbb/reader_writer_lock.cpp:21:
/usr/local/include/tbb/reader_writer_lock.h:21:9: warning: TBB Warning: tbb/reader_writer_lock.h is deprecated. For details, please see
      Deprecated Features appendix in the TBB reference manual. [-W#pragma-messages]
#pragma message("TBB Warning: tbb/reader_writer_lock.h is deprecated. For details, please see Deprecated Features appendix in the TBB r...
        ^
1 warning generated.
In file included from ../../src/tbb/spin_rw_mutex.cpp:23:
/usr/local/include/tbb/atomic.h:21:9: warning: TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in
      the TBB reference manual. [-W#pragma-messages]
#pragma message("TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
        ^
1 warning generated.
In file included from ../../src/tbb/x86_rtm_rw_mutex.cpp:26:
In file included from ../../src/tbb/governor.h:24:
/usr/local/include/tbb/task_scheduler_init.h:21:9: warning: TBB Warning: tbb/task_scheduler_init.h is deprecated. For details, please see
      Deprecated Features appendix in the TBB reference manual. [-W#pragma-messages]
#pragma message("TBB Warning: tbb/task_scheduler_init.h is deprecated. For details, please see Deprecated Features appendix in the TBB ...
        ^
In file included from ../../src/tbb/x86_rtm_rw_mutex.cpp:26:
In file included from ../../src/tbb/governor.h:27:
In file included from ../../src/tbb/tbb_misc.h:26:
/usr/local/include/tbb/atomic.h:21:9: warning: TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in
      the TBB reference manual. [-W#pragma-messages]
#pragma message("TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
        ^
../../src/tbb/x86_rtm_rw_mutex.cpp:83:30: error: no member named 'internal_set_mutex' in 'tbb::spin_rw_mutex_v3::scoped_lock'
            s.my_scoped_lock.internal_set_mutex(NULL);
            ~~~~~~~~~~~~~~~~ ^
../../src/tbb/x86_rtm_rw_mutex.cpp:129:34: error: no member named 'internal_set_mutex' in 'tbb::spin_rw_mutex_v3::scoped_lock'
                s.my_scoped_lock.internal_set_mutex(this);  // need mutex for release()
                ~~~~~~~~~~~~~~~~ ^
../../src/tbb/x86_rtm_rw_mutex.cpp:172:34: error: no member named 'internal_set_mutex' in 'tbb::spin_rw_mutex_v3::scoped_lock'
                s.my_scoped_lock.internal_set_mutex(this);  // need mutex for release()
                ~~~~~~~~~~~~~~~~ ^
2 warnings and 3 errors generated.
make[2]: *** [x86_rtm_rw_mutex.o] Error 1
make[1]: *** [tbb_release] Error 2
cp: tbb/build/lib_release/libtbb*.*: No such file or directory
make: *** [tbb] Error 1
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/Users/anirbanmukherjee/Library/R/3.6/library/RcppParallel’
Error: Failed to install 'RcppParallel' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpy4Vnx3/filec47f5eaf6274/RcppParallel_5.0.0.tar.gz’ had non-zero exit status

**Comment by kevinushey** [comment]
Thank you for the bug report! I believe this is now fixed in the development version of RcppParallel.

The underlying issue is that the wrong TBB headers were being found and used. We now ensure that the bundled TBB is found and used during installation.

**Comment by anirban-mukherjee** [comment]
Great. Thank you!

**Comment by kevinushey** [comment]
Awesome. Thanks for the quick response!
