### ISSUE TITLE
Error output.col() when using RcppParallel and RcppEigen

### ISSUE THREAD

**Issue by tracquangthinh** [RcppCore/RcppParallel#116]
Hi, 
I am having a problem to set a column of output matrix when using `RcppParallel` and `RccpEigen`.  Not sure but likely this is a bug.

Normally, I can easily set it by using` .col()`. For example:

```
MatrixXd test(){
  VectorXd newCol(2);
  newCol[0] = 4;
  newCol[1] = 6;
  MatrixXd out = MatrixXd::Zero(2, 2);
  out.col(0) = newCol;
  return out;
}
```
However, I could not use this function with `RcppParallel` (core dump). I can use a loop to set for each cells so I think `col()` maybe has some problems.

Best,
Thinh.

**Comment by kevinushey** [comment]
Sorry, but without a minimally reproducible example there's not much I can do to help.

My only suspicion is that you're doing something that is perhaps not thread-safe.

**Comment by tracquangthinh** [comment]
Sorry, I forgot to put my example. My code is quite long so I wrote a similar code:

```
struct Test : public Worker
{
   const MatrixXd& X;
   const MatrixXd& y;
   
   MatrixXd& out;
   
   Test(const MatrixXd& X, const MatrixXd& y, MatrixXd& out) 
      : X(X), y(y), out(out) {}
   
  void operator()(std::size_t begin, std::size_t end) {
    int nRow = out.rows();
    for(unsigned i = begin ; i < end ; i++){
      VectorXd res = VectorXd::Ones(nRow);
      out.col(i) = res;
     }
   }
};

// [[Rcpp::export]]
MatrixXd parallelTest(MatrixXd X, MatrixXd y) {

  // allocate the output matrix
  MatrixXd out = MatrixXd::Zero(X.cols(), y.rows());

  Test test(X, y, out);

  parallelFor(0, y.cols(), test);
  
  return out;
}
```
Simply, I have `out` matrix and for each thread, I want to calculate some thing and then set a column of `out` by return value. As you suggested, I think it's not thread safe. Do you have any suggestions? Thanks!

**Comment by tracquangthinh** [comment]
I forgot to use RMatrix as you suggested. But seems RMatrix does not support some thing like a wrapper for RCppEigen. I will close this issue.
Anw, thank you for your support!
