### ISSUE TITLE
A Question-Not issue

### ISSUE THREAD

**Issue by NedaJalali-codes** [RcppCore/RcppParallel#117]
Hi,
I have a question about RcppParallel. I saw the examples that you provided to clarify how we can use the package. The situation is clear when we have a vector or matrix. I wonder if we can use RcppParallel when we have arma::cube. 
Thank you

**Comment by eddelbuettel** [comment]
It probably depends.  For many Armadillo data structures, particularly the vectors and matrices, we pass the R object "through".  No copy is made, it is efficient -- but it also means R memory is re-used!

Which is a no-no for RcppParallel (and OpenMP code in general).   

I would have to check to sure but I _think_ this is the same for cube.

**Comment by NedaJalali-codes** [comment]
Thank you so much.
