### ISSUE TITLE
RcppParallel on FreeBSD didn't compile the included TBB lib?

### ISSUE THREAD

**Issue by jszhao** [RcppCore/RcppParallel#124]
Today, I try to install rstan on FreeBSD, and got error like:

```
...
rstan.so: Undefined symbol "_ZN3tbb8internal26task_scheduler_observer_v37observeEb"
...
```
(please refer to [rstan fails to be installed on FreeBSD](https://github.com/stan-dev/rstan/issues/805))

After some struggle, we located the issue come from `libtbb` is not linked to `rstan.so`. And `libtbb` is assumed to be provided by `RcppParallel`. However, I inspected the libs installed by `RcppParallel`, and did not find `tbb` related libs. And `LdFlags()` return nothing.

I don't know how to configure `RcppParallel` during installation in order to make it to install the `tbb` libs. or `tbb` is not supported by FreeBSD? In fact, there is a package call `tbb-2020.3` in the pkg system of FreeBSD.

**Comment by kevinushey** [comment]
Compilation of TBB on FreeBSD isn't enabled, simply because we weren't able to find the time to test and make sure that works. This is where we toggle compilation of TBB (via the `USE_TBB` make variable):

https://github.com/RcppCore/RcppParallel/blob/394a7295ea018a5863cbe76ccba86ff295e4a5f8/src/Makevars.in#L5-L48

And this is where we indicate to the C preprocessor whether we're using TBB:

https://github.com/RcppCore/RcppParallel/blob/394a7295ea018a5863cbe76ccba86ff295e4a5f8/inst/include/RcppParallel.h#L8-L18

A PR would be appreciated to enable TBB support on FreeBSD.

**Comment by jszhao** [comment]
Thanks for the response. It's not easy to patch the source of `tbb` itself to work on FreeBSD.  I have patch the file you mentioned, but errors appear during the compilation of `tbb` lib. Because there is a package on FreeBSD, named `tbb-2020.3`. Is it possible to tweak `RcppParallel` to use the installed `tbb` libs? Thanks!

**Comment by kevinushey** [comment]
It should be possible to patch RcppParallel to use a system-install of TBB -- in fact, Debian does exactly that:

https://sources.debian.org/patches/r-cran-rcppparallel/5.0.2+dfsg-1/use_debian_packaged_libtbb.patch/

I'd like to eventually port a patch like this over to RcppParallel, but haven't yet found the time to do so.

**Comment by eddelbuettel** [comment]
Yes, nice plan!  This is being done in a few packages. [`nloptr`](https://github.com/jyypma/nloptr) is one (for which I wrote that `configure` logic).

**Comment by kevinushey** [comment]
It should now be possible to handle this with the latest release of RcppParallel. You can do something like:

```
export TBB_LIB=/path/to/tbb/lib
export TBB_INC=/path/to/tbb/inc
R CMD INSTALL RcppParallel
```

and RcppParallel will instead use the version of TBB you have directed it to, rather than its bundled version.

**Comment by jszhao** [comment]
> It should now be possible to handle this with the latest release of RcppParallel. You can do something like:
> 
> ```
> export TBB_LIB=/path/to/tbb/lib
> export TBB_INC=/path/to/tbb/inc
> R CMD INSTALL RcppParallel
> ```

Thanks a lot for fixing this issue. 

Is it possible to install the package in R console using "install.packages". I don't know how to pass the environmental variable TBB_LIB and TBB_INC into the function.

**Comment by kevinushey** [comment]
Yes, you can use `Sys.setenv()`; e.g.

```
Sys.setenv(TBB_LIB = "/path/to/tbb/lib")
Sys.setenv(TBB_INC = "/path/to/tbb/include")
install.packages("RcppParallel", type = "source")
```

**Comment by jszhao** [comment]
@kevinushey Thanks a lot. It works.

**Comment by kevinushey** [comment]
Great, glad to hear it!
