### ISSUE TITLE
Error in file(con, "r") : cannot open the connection

### ISSUE THREAD

**Issue by Murashova** [RcppCore/RcppParallel#127]
I was running my first stan model, see code below:
`# set seed for replicability
set.seed(8675309)

## create a N x k matrix of covariates
N = 250
K = 3

covariates = replicate(K, rnorm(n=N))
colnames(covariates) = c('X1', 'X2', 'X3')

## create the model matrix with intercept
X = cbind(Intercept=1, covariates)

## create a normally distributed variable that is a function of the covariates
coefs = c(5, .2, -1.5, .9)
mu = X %*% coefs
sigma = 2
y = rnorm(N, mu, sigma)

## Run lm for later comparison; but go ahead and examine now if desired
modlm = lm(y~., data=data.frame(X[,-1]))

summary(modlm)

## Create the data list object for Stan input
dat = list(N=N, K=ncol(X), y=y, X=X)

## Create the stan model object using Stan's syntax
stanmodelcode = "
data {                      // Data block
int<lower=1> N;           // Sample size
int<lower=1> K;           // Dimension of model matrix
matrix[N, K] X;           // Model Matrix
vector[N] y;              // Target variable
}

/* 
transformed data {          // Transformed data block. Not used presently.
} 
*/

parameters {                // Parameters block
vector[K] beta;           // Coefficient vector
real<lower=0> sigma;      // Error scale
}

model {                     // Model block
vector[N] mu;
mu = X * beta;            // Creation of linear predictor

// priors
beta ~ normal(0, 10);
sigma ~ cauchy(0, 5);     // With sigma bounded at 0, this is half-cauchy

// likelihood
y ~ normal(mu, sigma);
}

/*
generated quantities {      // Generated quantities block. Not used presently.
}
*/
"
##Running the Model

library(rstan)
##library(rtools40)
##rstan_options(auto_write = TRUE)

##rstan::stan(model, data)

mc.cores = parallel::detectCores()
rstan_options(auto_write = TRUE)

## Run the model and examine results
fit = stan(model_code = stanmodelcode,
           data = dat,
           iter = 5000,
           warmup = 2500,
           thin = 10,
           chains = 4)
`

But has been getting the following message:

Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  'C:/Users/NMURAV~1/AppData/Local/CONTIN~1/ANACON~1/Library/usr/mingw_/bin/g++' not found
2: In readLines(file.path(makevar_files)) :
  incomplete final line found on 'C:/Users/nmuravskaya/Documents/.R/Makevars.win'
3: In readLines(old_path) :
  incomplete final line found on 'C:/Users/nmuravskaya/Documents/.R/Makevars.win'
4: In system(cmd, intern = !verbose) :
  running command 'C:/Users/NMURAV~1/DOCUME~1/R/R-40~1.2/bin/x64/R CMD SHLIB file1dd1823062c48.cpp 2> file1dd1823062c48.cpp.err.txt' had status 1
5: In file(con, "r") :
  cannot open file 'file1dd1823062c48.cpp.err.txt': No such file or directory
Error in sink(type = "output") : invalid connection

For the information:
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.21.2         ggplot2_3.3.2        StanHeaders_2.21.0-6

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         compiler_4.0.2     pillar_1.4.6       prettyunits_1.1.1  tools_4.0.2        pkgbuild_1.1.0    
 [7] jsonlite_1.7.0     lifecycle_0.2.0    tibble_3.0.3       gtable_0.3.0       pkgconfig_2.0.3    rlang_0.4.7       
[13] cli_2.0.2          rstudioapi_0.11    parallel_4.0.2     curl_4.3           loo_2.3.1          gridExtra_2.3     
[19] dplyr_1.0.1        withr_2.2.0        generics_0.0.2     vctrs_0.3.2        tidyselect_1.1.0   stats4_4.0.2      
[25] grid_4.0.2         glue_1.4.1         inline_0.3.15      R6_2.4.1           processx_3.4.3     fansi_0.4.1       
[31] purrr_0.3.4        callr_3.4.3        magrittr_1.5       codetools_0.2-16   matrixStats_0.56.0 scales_1.1.1      
[37] ps_1.3.4           ellipsis_0.3.1     assertthat_0.2.1   colorspace_1.4-1   V8_3.2.0           RcppParallel_5.0.2
[43] munsell_0.5.0      crayon_1.3.4

**Comment by kevinushey** [comment]
Unless I'm misunderstanding something, this doesn't appear to be an RcppParallel issue.

```
1: In system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  'C:/Users/NMURAV~1/AppData/Local/CONTIN~1/ANACON~1/Library/usr/mingw_/bin/g++' not found
```

It looks like you're trying to use a custom compiler on Windows in your Anaconda installation; you should use [Rtools](https://cran.r-project.org/bin/windows/Rtools/) on Windows.
