### ISSUE TITLE
How to set number of threads multiple times in RcppParallel 5.0.2

### ISSUE THREAD

**Issue by pcarbo** [RcppCore/RcppParallel#130]
Thanks all for a great package. We have been using extensively for some large-scale computation; e.g., for non-negative matrix factorization in our new [fastTopics](https://github.com/pcarbo/fastTopics) package.

The [changes](https://cran.r-project.org/web/packages/RcppParallel/NEWS) introduced in RcppParallel 5.0.2, however, break some important functionality. In particular, we would like to be able to set the number of threads on-the-fly for benchmarking the computations. (Apologies if this issue has already been mentioned in a previous GitHub issue.)

Will this functionality be re-introduced in future versions? If not, do you have a suggested workaround? e.g., by setting an environment variable using `Sys.setenv`?

**Comment by pcarbo** [comment]
I'm guessing this is related to Issue #122?

**Comment by kevinushey** [comment]
In the development version of `RcppParallel`, the number of threads to be used can be passed as an argument to `parallelFor()`:

https://github.com/RcppCore/RcppParallel/blob/394a7295ea018a5863cbe76ccba86ff295e4a5f8/inst/include/RcppParallel.h#L31-L45

Will that be sufficient? We could also implement the request to set the default number of threads via an environment variable.

**Comment by pcarbo** [comment]
That sounds good to me. Are you intending to submit a new release to CRAN anytime soon? (It isn't urgent — in the meantime, I will continue to use RcppParallel 5.0.1.)

I think it would also be helpful to throw a warning or error if `setThreadOptions` is called more than once in a session. I don't know how difficult that would be to achieve, but it would be very helpful. At the very least, there should be something in `help(setThreadOptions)` about this. Thanks.

**Comment by kevinushey** [comment]
I think what I ultimately may do is have `setThreadOptions()` set an environment variable, and use that environment variable as the default value for parallel computations without an explicit number of threads set. This should effectively give the same user-level behavior as RcppParallel 5.0.1.

**Comment by pcarbo** [comment]
That sounds like a good approach. I look forward to the updated interface.

**Comment by eddelbuettel** [comment]
Maybe also consider to `options("Ncpus")` ?
