### ISSUE TITLE
licensing: permission to use GPL2 or later

### ISSUE THREAD

**Issue by jlmelville** [RcppCore/RcppParallel#134]
Hello, RcppParallel is GPL2-only (although some of the tests are GPL2 or later). Does this cause problems for packages that are LinkingTo this project but which are GPL2 or later, or GPL3+? If so, is there a way to get permission to distribute a derivative work as GPL3+?

Context: I stopped using RcppParallel for some packages when TBB was causing CRAN check errors but kept some code from RcppParallel in a header file that allowed me to implement the parallel for code with the C++11 thread support (i.e. no tinythread or TBB). Unfortunately my package is GPL3+ and I have been asked to either relicense my package or get permission to redistribute that code as GPL3+. Now would be a good time to switch back to linking to RcppParallel directly, but I don't think that would solve the licensing problem as I still would have to include a GPLv2-only header file.

**Comment by kevinushey** [comment]
This seems fine to me -- we could re-license as `GPL (>= 2)`, so that users are free to use it under the version of the GPL version most appropriate. @eddelbuettel; @jjallaire; does that sound okay?

**Comment by eddelbuettel** [comment]
Yes it is a pretty common choice (as lawyers insist that 2 cannot be mixed with 3, but >=2 can so ...).

**Comment by jjallaire** [comment]
Yes that would be fine with me as well.

**Comment by kevinushey** [comment]
Done!

**Comment by jlmelville** [comment]
Many thanks for the swift action (on behalf of both myself and the several other authors of GPL3-licensed packages that were in non-compliance)!
