### ISSUE TITLE
update bundled TBB to support newer M1 ARM macOS

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/RcppParallel#137]
R is hoping to officially support M1 macOS machines with the R 4.1.0 release (planned for next Spring), but the bundled version of TBB does not compile on those machines currently.

We should update TBB + RcppParallel on CRAN before the next R release.

**Comment by elbamos** [comment]
I was able to compile on M1 against oneTBB, but the resulting package fails to function (it emits warnings on load that it cannot find libtbb or libmalloctbb) because it looks for libraries with the .so suffix rather than .dylib. 

```
> library(RcppParallel)
Warning messages:
1: In fun(libname, pkgname) :
  TBB library /opt/homebrew/Cellar/tbb/2020_U3_1/lib/libtbb.so not found.
2: In fun(libname, pkgname) :
  TBB malloc library /opt/homebrew/Cellar/tbb/2020_U3_1/lib/libtbbmalloc.so not found.
```

```
/opt/homebrew/Cellar/tbb/2020_U3_1/lib] [base] stable ± ls
cmake                    libtbb.dylib             libtbbmalloc.dylib       python3.9
libtbb.a                 libtbbmalloc.a           libtbbmalloc_proxy.dylib
```

Hope this is helpful to you in some way.

**Comment by anirban-mukherjee** [comment]
I get the same errors on an Intel Mac using system OneAPI TBB instead of the bundled TBB. Code using RcppParallel, however, works. I just ignore the two warnings. See: https://github.com/RcppCore/RcppParallel/issues/157

**Comment by kevinushey** [comment]
I think this should be resolved in the latest release of RcppParallel. Please file a new issue with extra context if you're still having trouble.

**Comment by jianshu93** [comment]
Hello All, 

I have the same error with R4.1.2 on M1 pro ARM. Solve available yet?

Thanks,

Jianshu
