### ISSUE TITLE
Install Intel TBB separately

### ISSUE THREAD

**Issue by MySchizoBuddy** [RcppCore/RcppParallel#14]
It isn't clear from reading the documentation that whether Intel TBB has to be installed separately

**Comment by jjallaire** [comment]
No, it's part of the package. See here:
http://rcppcore.github.io/RcppParallel/

**Comment by MySchizoBuddy** [comment]
In that case it should mention which version of TBB is included

**Comment by jjallaire** [comment]
The package major/minor version corresponds to the TBB version. I'll update
the docs accordingly
