### ISSUE TITLE
ERROR: configuration failed for package ‘RcppParallel’ on Ubuntu LTS 18.04.5

### ISSUE THREAD

**Issue by panoptikum** [RcppCore/RcppParallel#140]
Dear Folks,

First let me thank you for your work!

This week I've updated a few packages, after the updates were done I could no longer use the [prophet package](https://github.com/facebook/prophet/issues/1750). I've removed my whole R-base, but now I can not install RcppParallel. The installation of other packages works. I am bit clueless since the error message does not reveal much:

```
** using staged installation
Rscript execution error: No such file or directory
ERROR: configuration failed for package ‘RcppParallel’
* removing ‘/usr/local/lib/R/site-library/RcppParallel’
```

I've tried installing older versions of RcppParallel but had no luck with this way.

Any hints are much appreciated!

Felix

**Comment by panoptikum** [comment]
I've found the solution [here](https://forum.knime.com/t/path-to-r-home-failed/16525/10). How is it possible that some r packages know where R Home is or don't they need to know the location for their installation? I'm a bit puzzled by this fact. Since other packages ran smoothly, I would not have expected this to be the issue. What is the difference between which R and Rhome? If I type R into the CLI I would expect that it knows where itself is located.

**Comment by eddelbuettel** [comment]
This suggests something unusual in your setup such as R outside $PATH or multiple.  Because generally:

```sh
edd@rob:~$ R RHOME                  # standard R from the Ubuntu build at R
/usr/lib/R
edd@rob:~$ RD RHOME                 # locally built r-devel, shell front-end
/usr/local/lib/R-devel/lib/R
edd@rob:~$ 
```

But in essence the error must be yours as the package builds and checks at CRAN.  So thanks for closing!

**Comment by panoptikum** [comment]
Additional information: During my re-installation I probably had compiled R from source which interfered with my other installation and was not removed by apt-get remove r-base.

**Comment by panoptikum** [comment]
> This suggests something unusual in your setup such as R outside $PATH or multiple. Because generally:
> 
> ```shell
> edd@rob:~$ R RHOME                  # standard R from the Ubuntu build at R
> /usr/lib/R
> edd@rob:~$ RD RHOME                 # locally built r-devel, shell front-end
> /usr/local/lib/R-devel/lib/R
> edd@rob:~$ 
> ```
> 
> But in essence the error must be yours as the package builds and checks at CRAN. So thanks for closing!

Yes, I think my previous confirms your reasoning.

**Comment by eddelbuettel** [comment]
It's all explained in the explicit  [R Installation and Administration](https://cran.r-project.org/doc/manuals/r-release/R-admin.html) manual.  You diverted from that, stuff may happen then.
