### ISSUE TITLE
Grainsize calculation on TinyThreads

### ISSUE THREAD

**Issue by franzbischoff** [RcppCore/RcppParallel#142]
https://github.com/RcppCore/RcppParallel/blob/39303ec773880111435bc7b735ea47703ad87658/inst/include/RcppParallel/TinyThread.h#L68

I was working fine with TBB in my app on Windows, defining the grainsize, but I got problems when porting to Linux and using TinyThreads. So I looked at the code.

Here I can see that, if I have a vector of size `767`, and I set the grainsize to `64` I get the following:

1. Total threads is `8`
2. So, `767/8` is not exact, and the algorithm chooses to do `767/(8-1) ~= 109`
3. So each chunk will be of size `109`. That is fine for my algorithm that needs a chunk larger than, let's say, `60`.
4. There will be `767 / 109 = 7.0366` jobs. That means one job will be of size `4` that is below my grainsize of `64`. And this will break my algorithm.

So, what about the last chunk to be of size `113` instead of `109` + `4`? This will be in conformity with what is expected from grainsize.

I can write a pull request. For now, I'm just discussing the case.

**Comment by franzbischoff** [comment]
Fix:

```c++
  // allocate ranges
  std::vector<IndexRange> ranges;
  std::size_t begin = range.begin();
  std::size_t end = begin;
  while (begin < range.end()) {
    if ((range.end() - (begin + grainSize)) < grainSize)
      end = range.end();
    else
      end = std::min(begin + grainSize, range.end());

    ranges.push_back(IndexRange(begin, end));
    begin = end;
  }
```

**Comment by kevinushey** [comment]
Thanks for the bug report + investigation. I agree with your assessment; would you be willing to write a pull request?

**Comment by franzbischoff** [comment]
Sure, asap

**Comment by kevinushey** [comment]
Looks like this was fixed in https://github.com/RcppCore/RcppParallel/pull/146 -- thanks again for the PR!
