### ISSUE TITLE
Does RMatrix support sparse matrices?

### ISSUE THREAD

**Issue by mmp3** [RcppCore/RcppParallel#143]
Does the `RMatrix` wrapper for `RcppParallel` "work" for sparse matrices?

In particular, I have a sparse matrix of type `dgCMatrix` from the `Matrix` package of `R`, and I want to do some computations on each column of the matrix in parallel via `RcppParallel`. The computations do not involve matrix operations, so there is no desire to use any matrix functions from e.g. Armadillo or Eigen.

The documentation for `RcppArmadillo` carefully does not mention compatibility with `RcppParallel`. The documentation of `RcppParallel` does not specify if `RMatrix` handles sparse matrices, though it does say "matrices of various types" without further elaboration.

The computations are performed column-wise and are embarrassingly parallel between each column. Is `RMatrix` even necessary in this case? Should a sparse matrix from `R` just be passed as `NumericMatrix`?

**Comment by eddelbuettel** [comment]
No, it is a simple dense matrix with contiguous representation.  

It's _raison d'être_ is keeping memory away from R and possible interactions with `gc()` which is why you cannot use `Rcpp::NumericMatrix` or even `arma::mat` constructed the usual `RcppArmadillo` way (as zero copy using R memory).

**Comment by mmp3** [comment]
Thank you, @eddelbuettel . 

I interpret your answer to mean that `RMatrix` cannot be used on a sparse matrix, e.g. `dgCMatrix`.

However, if the computations do not involve race conditions (i.e. embarassingly parallel), does this mean that I can use `RcppParallel` to operate on e.g. an `sp_mat` from Armadillo directly?

**Comment by kevinushey** [comment]
In general, memory treated as read-only can be shared (read) across multiple parallel processes; it's only when you need to modify that memory do things become more complicated.

That said, I'm not sure whether Armadillo operations are in general thread safe -- it could depend on other factors; e.g. whether a multi-threaded BLAS is being used (?)

**Comment by eddelbuettel** [comment]
"Should be" as Conrad also uses OpenMP internally in Armadillo (if and where available...)

I have a very vague and fuzzy recollection that a user was once burned on read-only access too, but maybe that is (un-)wishful thinking.  I agree that it should work in principle and if done carefully.
