### ISSUE TITLE
lto-wrapper failed

### ISSUE THREAD

**Issue by JJHendry** [RcppCore/RcppParallel#156]
building gnumeric: first problem was I didn't have libxcrypt installed.  It isn't mentioned as a dependency but it is for the python plugin.  Second problem is on linking python plugin - "lto1: internal compiler error".  Is lto-wrapper missing?

**Comment by kevinushey** [comment]
Sorry, I have absolutely no idea.

**Comment by JJHendry** [comment]
Sorry Kevin,

	new to forum, didn't mean to put it on this thread!



On Mon, 08 Mar 2021 18:31:30 -0800
Kevin Ushey <notifications@github.com> wrote:

> Sorry, I have absolutely no idea.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/RcppCore/RcppParallel/issues/156#issuecomment-793283953


-- 
John Hendry <JJ_hendry@telstra.com>

**Comment by kevinushey** [comment]
No worries!
