### ISSUE TITLE
Installation error R 4.0.0. & R 3.6.1 CentOS Linux 7

### ISSUE THREAD

**Issue by opoyc** [RcppCore/RcppParallel#168]
When trying to install in multiple R versions I always get this error:

trying URL 'https://cran.rstudio.com/src/contrib/RcppParallel_5.1.2.tar.gz'
Content type 'application/x-gzip' length 1628228 bytes (1.6 MB)

downloaded 1.6 MB

* installing *source* package ‘RcppParallel’ ...
** package ‘RcppParallel’ successfully unpacked and MD5 sums checked
** using staged installation
** preparing to configure package 'RcppParallel' ...
** finished configure for package 'RcppParallel'
** libs
g++ -std=gnu++11 -I"/opt/R/4.0.0/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c init.cpp -o init.o
**g++ -std=gnu++11 -I"/opt/R/4.0.0/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c options.cpp -o options.o
options.cpp:2:26: fatal error: RcppParallel.h: No such file or directory
 #include <RcppParallel.h>
                          ^**
compilation terminated.
make: *** [options.o] Error 1
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/opt/R/4.0.0/lib/R/library/RcppParallel’
* restoring previous ‘/opt/R/4.0.0/lib/R/library/RcppParallel’
Warning in install.packages :
  installation of package ‘RcppParallel’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpjCrzN8/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

Session info:
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.0 tools_4.0.0    tinytex_0.27   xfun_0.19     

I've tried also R 3.6.1 and getting the same result. What could it be?

**Comment by kevinushey** [comment]
Do you have a local `~/.R/Makevars` file overriding `PKG_CXXFLAGS` or something similar?
