### ISSUE TITLE
RcppParallel library install error

### ISSUE THREAD

**Issue by Byeongiltak** [RcppCore/RcppParallel#170]
An error occurred while installing the RcppParallel library, but I do not know the cause.
What should I do?

install.packages("/home/usr/Downloads/R/packages/RcppParallel_5.0.2.tar.gz", repos=NULL, type="source")

I installed it with a normal user account.

***** error *****
installing source package 'RcppParallel' ...
** package 'RcppParallel' successfully unpacked and MD5 sums checked
** using staged installation
Rscript execution error: Permission denied
ERROR: configuration failed for package ‘RcppParallel’
** removing ‘/app/rserver/R_project/lib64/R/library/RcppParallel’

 In the case of root account
***** error *****
installing source package 'RcppParallel' ...
** package 'RcppParallel' successfully unpacked and MD5 sums checked
** using staged installation
Rscript execution error: No such file or directory
ERROR: configuration failed for package ‘RcppParallel’
** removing ‘/app/rserver/R_project/lib64/R/library/RcppParallel’

Session info:
R version 4.0.5
OS : RHEL 7.4

Help....

**Comment by kevinushey** [comment]
Sorry, but I have no idea. Note that the current version on CRAN is 5.1.4; you could try installing that instead.

**Comment by eddelbuettel** [comment]
Plus as not uncommon with RHEL/CentOS: your C++ compiler may be too old.

**Comment by Byeongiltak** [comment]
Upgrading CRAN 5.1.4 will cause the same problem.
Also, upgrading C++ to 8.3 causes the same problem.
What should I do?

**Comment by eddelbuettel** [comment]
Are you sure you are using g++ 8.3 from R? `R CMD config CXX` and `R CMD config CXX11` will tell you `g++`, likely. Does `g++ --version` then show 8.3?
