### ISSUE TITLE
Intel TBB 4.4.1 released

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/RcppParallel#18]
As I noticed because @thirdwing pointed to it:
https://www.threadingbuildingblocks.org/news/intel-tbb-4-4-update-1-released

**Comment by kevinushey** [comment]
Thanks to https://github.com/RcppCore/RcppParallel/commit/f5f62cc23db0d03c82b9463b88a6d000f2bafc14, we're now using a freshly minted TBB.
