### ISSUE TITLE
Cannot load: undefined symbol tbb::task::note_affinity

### ISSUE THREAD

**Issue by Enchufa2** [RcppCore/RcppParallel#183]
Are we sure that nothing is required on Linux?

https://github.com/RcppCore/RcppParallel/blob/0da9610af0fcfe3154bff8c0e38c9ad22fc9fb62/R/tbb.R#L92-L93

I cannot load the `markovchain` package (cc @spedygiorgio), which links against `RcppParallel`, with the following error:

```
Error: package or namespace load failed for ‘markovchain’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/markovchain/libs/markovchain.so':
  /usr/local/lib/R/library/markovchain/libs/markovchain.so: undefined symbol: _ZN3tbb4task13note_affinityEt
```

So somehow this TBB symbol ends up in the `markovchain` library. Manually adding `-ltbb` to the linking phase solves the issue for me, but currently `RcppParallel::RcppParallelLibs()` returns nothing for Linux.

**Comment by eddelbuettel** [comment]
We can compare notes, I can on the courtesy Linux VM I use for Rcpp testing which has a _ton_ of packages in `~/tmp/lib`:

```r
R> .libPaths()
[1] "/home/dirk/tmp/lib"            "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"       "/usr/lib/R/library"           
R> library("markovchain")
Package:  markovchain
Version:  0.9.0
Date:     2022-07-01
BugReport: https://github.com/spedygiorgio/markovchain/issues

R> 
```

All CRAN, all current, on Debian testing (also current).

**Comment by Enchufa2** [comment]
With system or bundled tbb?

**Comment by eddelbuettel** [comment]
Ah yes, I am likely using the bundled one.

**Comment by Enchufa2** [comment]
Then that's most probably the issue. It should be easy to fix the behavior of `LdFlags()` depending on whether the package was built using a user-provided TBB_LIB, or an auto-detected one as proposed in #178. I'll look into this when I find time.

**Comment by Enchufa2** [comment]
Cannot reproduce this anymore.
