### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by DarioS** [RcppCore/RcppParallel#184]
[Log](https://github.com/RcppCore/RcppParallel/files/9505898/error.txt) is attached.

```r
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Rocky Linux 8.6 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /apps/intel-oneapi/mkl/2022.1.0/lib/intel64/libmkl_intel_lp64.so.2
```

**Comment by kevinushey** [comment]
It looks like your compiler is being inferred as gcc:

```
make[1]: Entering directory '/scratch/vt74/ds6924/tmp/RtmptFuxZJ/R.INSTALL3ff42d3f5e9272/RcppParallel/src/tbb/src'
OS: linux
arch=intel64
compiler=gcc
runtime=cc8.5.0_libc2.28_kernel4.18.0
tbb_build_prefix=linux_intel64_gcc_cc8.5.0_libc2.28_kernel4.18.0
```

but the actual compiler here is `icpc` (Intel's compiler?)

Is there some simple way for me to stand up an environment using `icpc` to test?

**Comment by kevinushey** [comment]
The output of `R CMD config --all` would probably also be helpful.

**Comment by DarioS** [comment]
No, registration to the H.P.C. needs an Australian university e-mail account. I attach the [config report](https://github.com/RcppCore/RcppParallel/files/9522159/config.txt) which will hopefully help.

.

**Comment by kevinushey** [comment]
I pushed a change in https://github.com/RcppCore/RcppParallel/commit/229c08bb9ee29dff257e346abf1788cc6366faf3; can you let me know if that helps you get further? Install it with e.g.

```
remotes::install_github("RcppCore/RcppParallel")
```

**Comment by DarioS** [comment]
Same error on Rocky Linux H.P.C. Connecting to a small in-house server which is Debian 11, installation works the first time.

**Comment by kevinushey** [comment]
Sorry to hear it. Unfortunately, without access to an environment using the Intel icc / icpc compilers there's not much I can do to help. Pull requests are welcome.

**Comment by DarioS** [comment]
The system administrator explains that it is a known issue of RcppParallel depending on outdated TBB and solution is:
```
module load R/4.2.1
module load intel-compiler/2020.3.304
module load intel-tbb/2020.3.304

export TBB_VERSION=$INTEL_TBB_VERSION
export TBB=$INTEL_TBB_BASE
export TBB_INC=$TBB/include
export TBB_LIB=$TBB/lib
export TBB_USE_SYMLINKS=FALSE

R
> install.packages("RcppParallel") # success
```

> As you can see, you need to downgrade intel-tbb version to 2020.3.304. If you already installed some R packages using intel-compiler/2021.6.0 you may need to reinstall them with the intel-compiler/2020.3.304

**Comment by kevinushey** [comment]
Glad you got it working. Yes, the instructions for building RcppParallel with a separate TBB installation are documented in the README.
