### ISSUE TITLE
 RcppParallel::LdFlags() isn’t correctly handling spaces

### ISSUE THREAD

**Issue by Arizazcq97** [RcppCore/RcppParallel#188]
I was looking for a solution to the stan problem. A gentleman told me that I needed to solve the problem that  the RcppParallel package not correctly handling spaces in filepaths for the RcppParallel::LdFlags() flag command.

For details, see：https://discourse.mc-stan.org/t/help-can-someone-help-me-find-out-why-this-error-is-reported/29332/20

**Comment by kevinushey** [comment]
Thanks -- should now be fixed in the development version of RcppParallel. You can install it with:

```
remotes::install_github("RcppCore/RcppParallel")
```
