### ISSUE TITLE
Cannot replicate gallery example

### ISSUE THREAD

**Issue by travis-leith** [RcppCore/RcppParallel#190]
I am trying to replicate [this](https://gallery.rcpp.org/articles/parallel-matrix-transform/).

I have copied it verbatim. I have installed RcppParallel both the CRAN version and then with `remotes::install_github("RcppCore/RcppParallel")`. In both cases I get the following errors

![image](https://user-images.githubusercontent.com/29927084/201835674-8eee73da-49e3-46e9-8fb2-045b14033280.png)

Windows 10
R version 4.2.1

**Comment by travis-leith** [comment]
Turns out I just needed some more `using`s and `#include`s, which is not clear from the gallery, imo.

**Comment by eddelbuettel** [comment]
Can you document (short diff?) what changes you needed?  The Gallery examples are all actual code we process so at one point it was sufficient (and maybe still is on Linux).
