### ISSUE TITLE
CRAN asking for C++17

### ISSUE THREAD

**Issue by aadler** [RcppCore/RcppParallel#194]
My package [lamW](https://cran.r-project.org/package=lamW) depends on RcppParallel. Its [results tab](https://cran.r-project.org/web/checks/check_results_lamW.html) is now showing a note "Specified C++11: please update to current default of C++17". Is addressing this as simple as updatinge Makevars and Makevars.win to read `CXX_STD = CXX17` or will that create issues? Thank you

**Comment by eddelbuettel** [comment]
1. That's an ongoing in several places, see eg my tweet here https://twitter.com/eddelbuettel/status/1619196698693365762
2. _Nobody_ has (AFAIK) been asked to update a package, the check is not (AFAIK) "on" for uploads.  It's just that a few of use have seen note.
3. The note is in you package, RcppParallel.  So why do you ask here?  Did you maybe mean to email `rcpp-devel`?
4. Yes it is _exactly_ that easy.  See for example [thiss code search at GitHub's cran mirror for `CXX_STD = CXX17`](https://github.com/search?q=org%3Acran+%22CXX_STD+%3D+CXX17%22&type=code); feel free to vary for CXX14 or CXX20.

**Comment by eddelbuettel** [comment]
Actually, _even easier_ is to just remove the line from `Makevars` and `Makevars.win`.  Recall that we added these when C++11 was still new and barely support (esp on Windows) which got so much better with more recent `Rtools` (and other C++ compilers).  So one possibility now is to not speficify anything.  R 4.2.* will get you C++14 already as default; R 4.3.* will give you C++17.

**Comment by aadler** [comment]
Hi, @eddelbuettel.

Thanks. The reason I asked here is, as you surmised, because RcppParallel itself is why those lines are in Makevars (see [https://rcppcore.github.io/RcppParallel/#r_packages](https://rcppcore.github.io/RcppParallel/#r_packages)). I'm using Rtools3 so I'll still get the std:iterators issue from #191 and #192, but I know that's being taken care of. Thanks!

**Comment by eddelbuettel** [comment]
Oh I see -- thanks for the reminder, and my bad.  

`RcppParallel` was one of many packages switching to C++11 as it needed, and could now consider relaxing that.   We are getting into new territory here: some libraries will soon set new minimum values as _e.g._ some Boost libraries now need C++14 or better.

**Comment by eddelbuettel** [comment]
And apologies -- I have since learned that CRAN _does_ indeed require / suggest a CXX11 -> CXX17 update for CXX_STD, whether that is wise or not.  I just helped another package with a quick ad-hoc PR so if you need a second set of eyes let us know.

**Comment by aadler** [comment]
Thank you for the update and no need to apologize at all! I should have been clearer in my initial request.
