### ISSUE TITLE
RcppParallelLibs() example and CRAN

### ISSUE THREAD

**Issue by evanbiederstedt** [RcppCore/RcppParallel#212]
Hi there

The example in the documentation for added RcppParallel to R packages is the following:

https://rcppcore.github.io/RcppParallel/#r_packages

**src\Makevars**
```
PKG_LIBS += $(shell ${R_HOME}/bin/Rscript -e "RcppParallel::RcppParallelLibs()")
```

**src\Makevars.win**

```
PKG_CXXFLAGS += -DRCPP_PARALLEL_USE_TBB=1

PKG_LIBS += $(shell "${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe" \
              -e "RcppParallel::RcppParallelLibs()")

```

Question: is this CRAN compatible? The CRAN checks have been cracking down on `+=` and `${shell .. }` recently. GNU shell functions are not accepted. 

https://cran.r-project.org/doc/manuals/R-exts.html#Writing-portable-packages

If the above is not CRAN-acceptable, would it be possible to provide new best standards to the community?

According to the manual:

> 
> The use of ${shell ...} can be avoided by using backticks, e.g.
> 
> PKG_CPPFLAGS = `gsl-config --cflags`
> which works in all versions of make known[74](https://cran.r-project.org/doc/manuals/R-exts.html#FOOT74) to be used with R.
>

Thoughts?

Thanks for the help

**Comment by eddelbuettel** [comment]
The standard way around this to add `GNU make` as a `SystemRequirement` which is what the package does:

https://github.com/RcppCore/RcppParallel/blob/5aa08f8b546d2fa99372d02d7b6a50344fb09ff3/DESCRIPTION#L32

See WRE -- this is the standard 'out' when one needs or wants a real `make` binary.

**Comment by evanbiederstedt** [comment]
I understand now; apologies, I was confused. CRAN trauma, I suppose. 

Thanks @eddelbuettel

**Comment by eddelbuettel** [comment]
No worries.  We've all been there (see my now expanded comment for alternatives).
