### ISSUE TITLE
GNU make is a SystemRequirements.

### ISSUE THREAD

**Issue by liyi-1989** [RcppCore/RcppParallel#23]
I am creating a package using the `RcppParallel` package and using the setting from [http://rcppcore.github.io/RcppParallel/] for `src\Makevars` and `src\Makevars.win` files.

However, when I check the package with `devtools::check()`, it has a NOTE:

> * checking for GNU extensions in Makefiles ... NOTE
GNU make is a SystemRequirements.

Do you know how to solve this? or I can ignore this when I submit it ro CRAN?

Thanks!

**Comment by dselivanov** [comment]
I think, it's ok. I hadn't any problems while submitting to CRAN.

**Comment by liyi-1989** [comment]
OK, thank you so much!

**Comment by eddelbuettel** [comment]
This is not really the place for this question -- the r-package-devel list.

As for the NOTE, there are two known solutions:

- list GNU make in SystemRequirements
- rename the Makefile to GNUmakefile

We have packages using either approach.

**Comment by liyi-1989** [comment]
Thanks Dirk! I am using the first approach. I will try the second one.

**Comment by dselivanov** [comment]
Even after adding GNU make to SystemRequirements, CRAN throws this note.

**Comment by kevinushey** [comment]
The note is delivered regardless -- it doesn't mean that CRAN will reject your package. In the worst case, they might ask you to justify why you need GNU make over just using a more portable make syntax.

**Comment by liyi-1989** [comment]
OK, great! Thanks Kevin!
