### ISSUE TITLE
RcppParallel failing to install with the 4.9.3 toolchain

### ISSUE THREAD

**Issue by jimhester** [RcppCore/RcppParallel#25]
https://www.statistik.tu-dortmund.de/~ligges/3.3new/RcppParallel.Rcheck/00install.out has the output from Uwe's check. Seems to be a number of things which need to be changed in the Makevars. You should be able to check what version is being used by checking the `COMPILED_BY` make variable set to `gcc-4.9.3`.

**Comment by kevinushey** [comment]
Should be resolved with https://github.com/RcppCore/RcppParallel/commit/988229b1b9336bc184f60b9f2ed6ccfb27b5b4f1. Thanks!
