### ISSUE TITLE
Install/compilation failed  

### ISSUE THREAD

**Issue by huyue87** [RcppCore/RcppParallel#29]
Hi 

I have tried to install 'RcppParallel' from both CRAN and Github. It gave me the following attached error messages. Before this, I have loaded the R package, Intel TBB 4.4. My working environment is x86_64-pc-linux-gnu-library R 3.2.2.  Could you give me any hint that what cause the error ?

Thanks  

error message:
......
/scratch/ccCvgQ2R.s: Assembler messages:
/scratch/ccCvgQ2R.s:102: Error: no such instruction: `xend'
/scratch/ccCvgQ2R.s:170: Error: no such instruction: `xabort $255'
/scratch/ccCvgQ2R.s:290: Error: no such instruction: `xbegin .L24'
/scratch/ccCvgQ2R.s:556: Error: no such instruction: `xbegin .L49'
/scratch/ccCvgQ2R.s:867: Error: no such instruction: `xabort $255'
make[2]: *** [x86_rtm_rw_mutex.o] Error 1
make[2]: Leaving directory `/scratch/RtmpJArVzs/R.INSTALL381854892277/RcppParallel/src/tbb/build/lib_release'
make[1]: *** [tbb_release] Error 2
make[1]: Leaving directory `/scratch/RtmpJArVzs/R.INSTALL381854892277/RcppParallel/src/tbb/src'
cp: cannot stat `tbb/build/lib_release/libtbb*.*': No such file or directory
make: *** [tbb] Error 1
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/pica/h1/yueh/R/x86_64-pc-linux-gnu-library/3.2/RcppParallel’

The downloaded source packages are in
	‘/scratch/Rtmp3Reke3/downloaded_packages’
Warning message:
In install.packages("RcppParallel") :
  installation of package ‘RcppParallel’ had non-zero exit status

**Comment by kevinushey** [comment]
Sounds similar to the issue reported here: https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/558688

What compiler are you using, and what processor are you running with?

**Comment by huyue87** [comment]
My processor parameters are  'Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz'
And my compiler is ' gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) '

**Comment by kevinushey** [comment]
gcc 4.4.7 is quite old at this point; I would highly recommend you install the latest version of gcc (gcc 6.1) if at all possible -- especially to take advantage of features on the newer Intel Xeon processors. Odds are things would work as expected with an updated compiler.

**Comment by eddelbuettel** [comment]
For eg RcppArmadillo we had other folks on RHEL using g++ 4.4.* hit a dead end as the compiler is old. But there appear to be yum repos with g++ 4.8 or 4.9 which should get you up to speed.  

RcppParallel is a nice piece of technology, but it places some demands on its toolchain.

**Comment by huyue87** [comment]
I have tried to install RcppParallel by using gcc/4.9 and gcc/6.1.0
When using gcc/4.9, it still gave me the error as compilation failed.
When using gcc/6.1.0,  it can do compilation but give me the warning as:

warning: ‘template<class _Tp> struct std::has_trivial_copy_constructor’ is deprecated [-Wdeprecated-declarations]
 template<typename T> struct tbb_trivially_copyable { enum { value = std::has_trivial_copy_constructor<T>::value }; };

The error in the end is:

Error : .onLoad failed in loadNamespace() for 'RcppParallel', details:
  call: dyn.load(tbb, local = FALSE, now = TRUE)
  error: unable to load shared object '/pica/h1/yueh/R/x86_64-pc-linux-gnu-library/3.2/RcppParallel/lib/libtbb.so.2':
  /sw/comp/gcc/4.9.2_milou/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /pica/h1/yueh/R/x86_64-pc-linux-gnu-library/3.2/RcppParallel/lib/libtbb.so.2)
Error: loading failed
Execution halted
ERROR: loading failed

**Comment by huyue87** [comment]
It seems like when install the current version of RcppParallel from github,
 it requires  'GLIBCXX_3.4.21' from /sw/comp/gcc/4.9.2_milou/lib64/libstdc++.so.6. (lib from gcc/4.9.2)
While 'GLIBCXX_3.4.21' only exist in /sw/comp/gcc/6.1.0_milou/lib64/libstdc++.so.6. (lib from gcc/6.1.0)
Even though I had loaded compiler gcc/6.1.0 before running R and install package RcppParallel

**Comment by kevinushey** [comment]
It sounds like you might need to download the RcppParallel sources and patch the build scripts (as described in https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/558688):

> After flailing around for a bit, I found that I could build successfully by commenting out the following lines in the build/linux.gcc.inc file:
> 
> gcc 4.8 and later support RTM intrinsics, but require command line switch to enable them
> ifneq (,$(shell gcc -dumpversion | egrep  "^4\.[8-9]"))
>     RTM_KEY = -mrtm
> #endif

It's also possible that we need to update to a newer version of TBB to support compilation when using the newer Xeon processors.

**Comment by huyue87** [comment]
Hi Kevin

Thanks for your kindly help.
Now I have solved the installing problem with your suggestion and my friends' suggestion. 

Firstly, you are right. cpp/6.1.0 can compile RcppParallel while cpp/4.1.0 or /4.9.0 could not!

Secondly, my installing error changed from _'compiling failed'_ to _'requiring unexisted `GLIBCXX_3.4.21' from /sw/comp/gcc/4.9.2_milou/...  for loading'_ when I loaded cpp/6.1.0 as the compiler before running R.    (p.s. `GLIBCXX_3.4.21' exists in /sw/comp/gcc/6.1.0_milou/...)
The problem here is the running R was compiled with gcc/4.9 long time ago, which might lead to the messed path problem.

After re-installing R/3.3.0 with gcc/6.1.0 and continually using gcc/6.1.0 as compiler when running R, 'RcppParallel' (v.4.3.19) can be successfully installed.

Yue

**Comment by eddelbuettel** [comment]
Thanks for the feedback, and good to see your persistence paid off!

**Comment by kendonB** [comment]
I'm starting out using my organization's compute cluster and I'm running into a similar problem. @kevinushey, before I go down the rabbit hole of getting a new compiler on the cluster, can you let me know if you expect that this should work? The error message is displayed first, then the compiler is right down the bottom: ``gcc (GCC) 5.4.0``

```
> install.packages("RcppParallel")
Installing package into ‘/home/kendon.bell/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/RcppParallel_4.3.20.tar.gz'
Content type 'application/x-gzip' length 1560887 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

* installing *source* package ‘RcppParallel’ ...
** package ‘RcppParallel’ successfully unpacked and MD5 sums checked
** libs
mkdir -p ../inst/lib/; \
        cd tbb/src; \
        if [ -n "" ]; then \
           make cpp0x=1 compiler=clang CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib; \
        elif [ -n "gcc" ]; then \
           make cpp0x=1 compiler=gcc CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib; \
        else \
           make cpp0x=1 CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib; \
        fi; \
        cd ../..; \
        cp tbb/build/lib_release/libtbb*.* ../inst/lib/
make[1]: Entering directory `/tmp/Rtmpcbn7UB/R.INSTALL5b346802ebae/RcppParallel/src/tbb/src'
../build/common.inc:47: *** "" is not supported. Add build/.inc file with os-specific settings .  Stop.
make[1]: Leaving directory `/tmp/Rtmpcbn7UB/R.INSTALL5b346802ebae/RcppParallel/src/tbb/src'
cp: cannot stat `tbb/build/lib_release/libtbb*.*': No such file or directory
make: *** [tbb] Error 1
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/home/kendon.bell/R/x86_64-pc-linux-gnu-library/3.4/RcppParallel’

The downloaded source packages are in
        ‘/tmp/RtmpLXCKBu/downloaded_packages’
Warning message:
In install.packages("RcppParallel") :
  installation of package ‘RcppParallel’ had non-zero exit status
```

```
[kendon.bell@build-sb ~]$ gcc --version
gcc (GCC) 5.4.0
```

**Comment by kevinushey** [comment]
I think it should work. What do you see if you try to install the development version? E.g.

```R
devtools::install_github("RcppCore/RcppParallel")
```

What kind of operating system are you running with? The error message suggests that you might be using an OS that TBB does not recognize during compilation.

**Comment by kevinushey** [comment]
You might need to try defining the environment variables:

    export OS=Linux
    tbb_os=Linux

assuming you're in a Linux-like environment that's not recognized as such for some reason.

**Comment by kendonB** [comment]
These are the environment variables before changing:
```
kendon.bell@build-sb ~]$ echo $OS
RHEL6.3
kendon.bell@build-sb ~]$ echo $tbb_os
```
Then I run:
```
export OS=Linux
export tbb_os=Linux
```
Then this:
```
> devtools::install_github("RcppCore/RcppParallel")
Downloading GitHub repo RcppCore/RcppParallel@master
from URL https://api.github.com/repos/RcppCore/RcppParallel/zipball/master
Installing RcppParallel
'/share/easybuild/RHEL6.3/sandybridge/software/R/3.4.0-gimkl-2017a/lib64/R/bin/R'  \
  --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpS8MRVe/devtoolse6360cf8630/RcppCore-RcppParallel-d822b21'  \
  --library='/home/kendon.bell/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests

* installing *source* package ‘RcppParallel’ ...
** libs
mkdir -p ../inst/lib/; \
        cd tbb/src; \
        if [ -n "" ]; then \
           make stdver=c++0x compiler=clang CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib; \
        elif [ -n "gcc" ]; then \
           make stdver=c++0x compiler=gcc CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib; \
        else \
           make stdver=c++0x CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib; \
        fi; \
        cd ../..; \
        cp tbb/build/lib_release/libtbb*.* ../inst/lib/
make[1]: Entering directory `/tmp/RtmpS8MRVe/devtoolse6360cf8630/RcppCore-RcppParallel-d822b21/src/tbb/src'
../build/common.inc:66: *** "" is not supported. Add build/.inc file with os-specific settings .  Stop.
make[1]: Leaving directory `/tmp/RtmpS8MRVe/devtoolse6360cf8630/RcppCore-RcppParallel-d822b21/src/tbb/src'
cp: cannot stat `tbb/build/lib_release/libtbb*.*': No such file or directory
make: *** [tbb] Error 1
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/home/kendon.bell/R/x86_64-pc-linux-gnu-library/3.4/RcppParallel’
Installation failed: Command failed (1)
>
```

**Comment by kevinushey** [comment]
I suspect the `OS` environment variable is getting unset / reset somewhere. Can you try this from a shell?

```R
export tbb_os=linux
git clone --depth 1 https://github.com/RcppCore/RcppParallel
R CMD build RcppParallel
R CMD INSTALL RcppParallel_2017.7.0.tar.gz
```

If that doesn't work, then I suspect you'll just have to try patching the `common.inc` file here: https://github.com/RcppCore/RcppParallel/blob/master/src/tbb/build/common.inc#L19-L40

You might also want to share what the output of `uname` on your system is.

**Comment by kendonB** [comment]
Looks like all I needed to do was:

```
export tbb_os=linux
```
then it worked fine. It just needed to be a small 'l' on the linux. It appears to be working now. Thank you so much for your help, @kevinushey!

**Comment by kevinushey** [comment]
Awesome, glad you were able to get this sorted out!

**Comment by mt1022** [comment]
I have the same problem:
```
g++ -m64 -o x86_rtm_rw_mutex.o -c -MMD -DDO_ITT_NOTIFY -g -O2 -DUSE_PTHREAD -m64 -mrtm  -fpic -flifetime-dse=1 -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/x86_rtm_rw_mutex.cpp
/tmp/cctnKVlk.s: Assembler messages:
/tmp/cctnKVlk.s:25: Error: no such instruction: `xend'
/tmp/cctnKVlk.s:191: Error: no such instruction: `xbegin .L23'
/tmp/cctnKVlk.s:286: Error: no such instruction: `xabort $255'
/tmp/cctnKVlk.s:446: Error: no such instruction: `xbegin .L42'
/tmp/cctnKVlk.s:603: Error: no such instruction: `xabort $255'
make[2]: *** [x86_rtm_rw_mutex.o] Error 1
make[2]: Leaving directory `/tmp/Rtmp4ceyIi/R.INSTALLdcb837d0805a/RcppParallel/src/tbb/build/lib_release'
make[1]: *** [tbb_release] Error 2
make[1]: Leaving directory `/tmp/Rtmp4ceyIi/R.INSTALLdcb837d0805a/RcppParallel/src/tbb/src'
cp: cannot stat `tbb/build/lib_release/libtbb*.*': No such file or directory
make: *** [tbb] Error 1
ERROR: compilation failed for package 'RcppParallel'
```

my gcc version:
```
$ gcc --version | head -1  # gcc (GCC) 7.2.0
```
my system info:
```
uname  #Linux
```
I followed the suggestions above:
```
export tbb_os=linux
git clone --depth 1 https://github.com/RcppCore/RcppParallel
```
and commented out the following section in `src/tbb/build/linux.gcc.inc`:
```
 # gcc 4.8 and later support RTM intrinsics, but require command line switch to enable them
 ifneq (,$(shell gcc -dumpversion | egrep  "^(4\.[8-9]|[5-9])"))
     RTM_KEY = -mrtm
 endif
```
Then I ran:
```
R CMD build RcppParallel
R CMD INSTALL RcppParallel_4.4.0.9000.tar.gz
```
This time the package was successfully installed. The only thing I am not sure about is whether there are any bad consequences after commenting out the `RTM_KEY = -mrtm` block in `linux.gcc.inc`?

**Comment by kvshams** [comment]
Getting similar issue in Mac OS Mojave (10.14.5)

```
.........
/usr/local/opt/llvm/bin/clang++ -fopenmp -I"/usr/local/Cellar/r/3.6.0_3/lib/R/include" -DNDEBUG   -I/usr/local/opt/gettext/include -I/usr/local/opt/llvm/include -std=gnu++11 -I../inst/include/ -DRCPP_PARALLEL_USE_TBB=1 -fPIC  -g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe -c init.cpp -o init.o
/usr/local/opt/llvm/bin/clang++ -fopenmp -I"/usr/local/Cellar/r/3.6.0_3/lib/R/include" -DNDEBUG   -I/usr/local/opt/gettext/include -I/usr/local/opt/llvm/include -std=gnu++11 -I../inst/include/ -DRCPP_PARALLEL_USE_TBB=1 -fPIC  -g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe -c options.cpp -o options.o
/usr/local/opt/llvm/bin/clang++ -fopenmp -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/opt/gettext/lib -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib -L/usr/local/Cellar/r/3.6.0_3/lib/R/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib -o RcppParallel.so init.o options.o -L/usr/local/Cellar/r/3.6.0_3/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
installing to /usr/local/lib/R/3.6/site-library/00LOCK-RcppParallel/00new/RcppParallel/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘RcppParallel’:
 .onLoad failed in loadNamespace() for 'RcppParallel', details:
  call: dyn.load(tbbMalloc, local = FALSE, now = TRUE)
  error: unable to load shared object '/usr/local/lib/R/3.6/site-library/00LOCK-RcppParallel/00new/RcppParallel/lib/libtbbmalloc.dylib':
  dlopen(/usr/local/lib/R/3.6/site-library/00LOCK-RcppParallel/00new/RcppParallel/lib/libtbbmalloc.dylib, 10): Library not loaded: @rpath/libomp.dylib
  Referenced from: /usr/local/lib/R/3.6/site-library/00LOCK-RcppParallel/00new/RcppParallel/lib/libtbbmalloc.dylib
  Reason: image not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/3.6/site-library/RcppParallel’
```

**Comment by coordinatesystem** [comment]
> The only thing I am not sure about is whether there are any bad consequences after commenting out the `RTM_KEY = -mrtm` block in `linux.gcc.inc`?

I think the only negative consequence would be that it could run more slowly on CPUs that support RTM than it would otherwise. I don't know how much RTM benefits this particular piece of software. In Linux you can check if your CPU supports it by looking at the file `/proc/cpuinfo` - check the "flags" line to see if it includes `rtm`.

I was also able to fix the "Error: no such instruction:" issue without removing the `-mrtm` block by using a newer binutils:
- old/not working: binutils-2.20.51.0.2-5.48.el6.x86_64
- new/working: devtoolset-8-binutils-2.30-54.el6.x86_64

This makes it work even on systems that don't support RTM.

**Comment by breag3ry** [comment]
This is raising the dead but I thought I'd put this out there in case it might help somebody.

I was trying to install this package locally on my university's cluster and I kept getting the assembler messages
...
/tmp/cctnKVlk.s: Assembler messages:
/tmp/cctnKVlk.s:25: Error: no such instruction: `xend'
...


The cluster uses modules and I started with these loaded: gcc/8.1.0 and R/3.6.3
I tried modifying Makevars ... same errors.
I tried rolling back to gcc/4.9.3 ... same errors.
I loaded openmpi/gcc/4.9.3 ... installed without error.

So FYI to anybody else it looks like access to the openmpi libs was the secret sauce.

**Comment by jaclynbeca** [comment]
For anyone else still looking for solutions to this, I tried many different solutions in these threads, and found coordinatesystem's comment helped. On HPC, I loaded the latest binutils (module avail binutils, module load binutils/2.32 in my case) and it installed without issues.
