### ISSUE TITLE
Package linking problem

### ISSUE THREAD

**Issue by thk686** [RcppCore/RcppParallel#31]
I have a preliminary package using RcppParallel, which is terrific. I was able to use "devtools::load_all()", but when I try to build the package with "R CMD build ..." I get a linker error. Not sure what I'm missing in the Makevars.

Can you try: devtools::install_github("harmonica", "thk686")?

Thanks.

**Comment by kevinushey** [comment]
For reference, the linker error I see:

```
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/Users/kevinushey/Library/R/3.2/library/harmonica/libs/harmonica.so':
  dlopen(/Users/kevinushey/Library/R/3.2/library/harmonica/libs/harmonica.so, 6): Symbol not found: __ZN3tbb4task13note_affinityEt
  Referenced from: /Users/kevinushey/Library/R/3.2/library/harmonica/libs/harmonica.so
  Expected in: flat namespace
 in /Users/kevinushey/Library/R/3.2/library/harmonica/libs/harmonica.so
```

The missing symbol is (demangled):

```
$ c++filt __ZN3tbb4task13note_affinityEt
tbb::task::note_affinity(unsigned short)
```

I don't see a smoking gun for why this is occurring in your package, though. :/

**Comment by kevinushey** [comment]
Oh, this sounds like the same `Rcpp` issue where we have load errors if you don't import at least one symbol from the package.

You can add e.g.

```
importFrom(Rcpp,setThreadOptions)
```

to your `NAMESPACE` to fix this.

**Comment by thk686** [comment]
On Wed, Jun 22, 2016 at 10:45 PM, Kevin Ushey <notifications@github.com>
wrote:

> importFrom(Rcpp,setThreadOptions)


Brilliant. That works.

THK

**Comment by eddelbuettel** [comment]
@kevinushey Good catch.  Should we add a `RcppParallel.package.skeleton()` ?

**Comment by jjallaire** [comment]
The docs here describe the requirements:

https://rcppcore.github.io/RcppParallel/#r_packages

The user probably just missed these docs.

On Thu, Jun 23, 2016 at 8:18 AM, Dirk Eddelbuettel <notifications@github.com
