### ISSUE TITLE
undefined reference errors when building on Windows

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/RcppParallel#34]
I'm seeing the following errors during compilation:

```
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o RcppParallel.dll tmp.def options.o -L../inst/lib/x64/ -ltbb -ltbbmalloc -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-33~1.1PA/bin/x64 -lR
options.o: In function `task_scheduler_init':
C:\Users\Kevin\git\RcppParallel\src/../inst/include/tbb/task_scheduler_init.h:118: undefined reference to `tbb::task_scheduler_init::initialize(int, unsigned long long)'
options.o: In function `setThreadOptions':
C:\Users\Kevin\git\RcppParallel\src/options.cpp:27: undefined reference to `tbb::task_scheduler_init::initialize(int, unsigned long long)'
collect2.exe: error: ld returned 1 exit status
```

I feel like I've seen this before but can't recall what the issue was + how it was fixed. :/

```
> sessionInfo()
R version 3.3.1 Patched (2016-06-27 r70840)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
```

**Comment by kevinushey** [comment]
Bizarre! Things appear to work fine when manually building from the command line with a vanilla

```
R CMD build RcppParallel
R CMD INSTALL RcppParallel
```

Only when compiled from within RStudio does the build fail with these linker errors.

What seems quite strange is the reference used:

```
tbb::task_scheduler_init::initialize(int, unsigned long long)
```

Even though the definition of `initialize` is as:

```
void __TBB_EXPORTED_METHOD initialize( int number_of_threads, stack_size_type thread_stack_size );
```

where `stack_size_type` is just `std::size_t`, and hence normally `unsigned long`, not `unsigned long long`.

**Comment by kevinushey** [comment]
Okay, it looks like the compilation definitely fails with this particular invocation:

```
Rcmd.exe INSTALL --preclean --no-multiarch --with-keep.source RcppParallel
```

After removing the `--no-multiarch` flag, `RcppParallel` installs without a hitch, both within and outside of RStudio. The overarching question then is, why does installation fail with `--no-multiarch`?

**Comment by jjallaire** [comment]
I don't recall but this may be a known issue based on the various
machinations we use to build TBB. What is the setting within the .Rproj?

**Comment by kevinushey** [comment]
The `.Rproj` had `--no-multiarch --with-keep.source` so presumedly that has worked in the past; however, I now have no luck compiling with those specific flags + the 64bit version of R.

**Comment by jjallaire** [comment]
Okay, not sure what's the issue then :-\
