### ISSUE TITLE
need to copy objects instead of just moving them in join in parallelReduce

### ISSUE THREAD

**Issue by ParallelCoder** [RcppCore/RcppParallel#35]
Hi, I am writing parallelReduce Worker. In operator() I create map of lists and in join I want to join lists in maps with the same key. For those joins I wanted to use splice method, but copilator gives error that list from map from join method parametr is constant. Instead of splice I need to call insert, but when splice is O(1), then insert is O(n) and needs to copy items on list.

Am I doing something wrong, or is this the possible error/bug, because in last join in requeres to copy (n-1)/(n) parts of elements in all joins when doing parallelReduce?

**Comment by dselivanov** [comment]
@ParallelCoder It is hard to answer anything without seeing your code.

**Comment by kevinushey** [comment]
Closing due to lack of response.
