### ISSUE TITLE
Update License (?)

### ISSUE THREAD

**Issue by evolvedmicrobe** [RcppCore/RcppParallel#38]
As of this month, the Intel TBB is now released under Apache 2.0 instead of GPLv2.  See for example the FAQ here: https://www.threadingbuildingblocks.org/faq/10

```
Has Intel® TBB recently moved from GPL to Apache license?

Yes. Intel TBB was under GPL license until August 2016. As of September 2016 Intel TBB is relicensed under Apache v2.0 license.

```

Apache is a bit less of a headache than GPLv2, would there be any interest in upgrading to this version and updating the README if this were to become a PR?

**Comment by eddelbuettel** [comment]
> Apache is a bit less of a headache than GPLv2

R and Rcpp are both GPL (>= 2) so the aggregate will always be GPL.

**Comment by evolvedmicrobe** [comment]
Ah, good point.  Yeah, no sense in upgrading if it won't make a difference.  Thanks for the quick response.
