### ISSUE TITLE
Problems Compiling Rcpp-parallel on OSX

### ISSUE THREAD

**Issue by zachcp** [RcppCore/RcppParallel#40]
Hi Team RcppParallel,

Thanks for your awesome package. I've been trying to package rcpp-parallel in [Bioconda](https://bioconda.github.io/) so that other packages that depend on Rcppparallel, like [dada2](https://github.com/benjjneb/dada2), can also be packaged up.  I've been running into a few issues compiling RcppParallel and I was wondering if someone might be able to take a look. Basically there is some sort of linking error during compilation; any help/pointers would be very much appreciated.

https://github.com/bioconda/bioconda-recipes/issues/3340
https://github.com/bioconda/bioconda-recipes/pull/3347

Thanks,
zach cp

**Comment by kevinushey** [comment]
Can you provide some more information on the build system? How was R built and installed? Why exactly do you need to invoke `install_name_tool` on the TBB shared libraries here?

Also, what is the output of `R CMD config SHLIB_LDFLAGS`? E.g. I see:

```
$ R CMD config SHLIB_LDFLAGS
-dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress
```

And so `-Wl,-headerpad_max_install_names` is already used there (although this will be for `RcppParallel.so`).

You can also try patching the TBB build scripts; odds are you need to play around in e.g. https://github.com/RcppCore/RcppParallel/blob/master/src/tbb/build/macos.clang.inc.

**Comment by zachcp** [comment]
Hi @kevinushey,

Thank you for your time. The basic backstory for bioconda is that it is a repository of pre-built cross-system binary files.  The original packages were largely C++/python but there are now tools in many languages including R.  All aspects of the build environment are specified in an environment file and in the case of R, the prebuilt R packages are used. 
The environment file for this build:

```yaml
package:
  name: r-rcppparallel
  version: "4.3.20"

source:
  fn: RcppParallel_4.3.20.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/RcppParallel_4.3.20.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/RcppParallel/RcppParallel_4.3.20.tar.gz

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-bh >=1.60.0_1
    - gcc   # [linux]
    - llvm  # [osx]
    - r
```


The output of the  `R CMD config SHLIB_LDFLAGS` in the build system is the following:

```-dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress``` 

Hmmm.  So you're right, the -headerpad_max_install is already in place. However, this is the error message from the build:

```
Fixing permissions
Fixing linking of libtbb.dylib in /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbb.dylib
Fixing linking of /usr/lib/libSystem.B.dylib in /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbb.dylib
Fixing linking of @rpath/./libgfortran.3.dylib in /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbb.dylib
Fixing linking of @rpath/./libstdc++.6.dylib in /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbb.dylib

install_name_tool -add_rpath @loader_path/../../../../ /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbb.dylib

Fixing linking of libtbbmalloc.dylib in /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbbmalloc.dylib
Fixing linking of /usr/lib/libSystem.B.dylib in /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbbmalloc.dylib
Fixing linking of @rpath/./libgfortran.3.dylib in /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbbmalloc.dylib

install_name_tool -add_rpath @loader_path/../../../../ /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbbmalloc.dylib

Fixing linking of libtbbmalloc_proxy.dylib in /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbbmalloc_proxy.dylib
Fixing linking of /usr/lib/libSystem.B.dylib in /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbbmalloc_proxy.dylib
Fixing linking of libtbbmalloc.dylib in /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbbmalloc_proxy.dylib
Fixing linking of @rpath/./libgfortran.3.dylib in /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbbmalloc_proxy.dylib
Fixing linking of @rpath/./libstdc++.6.dylib in /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbbmalloc_proxy.dylib


install_name_tool -add_rpath @loader_path/../../../../ /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbbmalloc_proxy.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /Users/zachpowers/anaconda3/conda-bld/r-rcppparallel_1483502920303/_b_env_placeh/lib/R/library/RcppParallel/lib/libtbbmalloc_proxy.dylib (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)

install_name_tool failed with exit status 1
```


So yes, it looks like an issue with the TBB libs. I will take a look but would also appreciate any tips on directions to take.

**Comment by zachcp** [comment]
@kevinushey 

It looks like I got everything to compile. I patched the TBB build line exactly as you suggested. Thank for your help!


https://github.com/bioconda/bioconda-recipes/pull/3347

as a parting thought - would it make sense to include these flags in your build?
