### ISSUE TITLE
Register native routines + erroneous line in NEWS

### ISSUE THREAD

**Issue by jolars** [RcppCore/RcppParallel#49]
There are CRAN NOTEs about native routines registration. From [the latest travis-ci build](https://travis-ci.org/RcppCore/RcppParallel/builds/271889043):

```
File ‘RcppParallel/libs/RcppParallel.so’:
  Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’
It is good practice to register native routines and to disable symbol
search.
```

I tried to fix this in a [pull request](https://github.com/RcppCore/RcppParallel/pull/48) at one point but abandoned the change because the build crashed on OSX. I, however, forgot to remove the line I had added in the NEWS:

https://github.com/RcppCore/RcppParallel/blob/f597d4b1a8632edb633cb5db9735cb0085e593a7/inst/NEWS#L7

My attempt entailed running `tools::package_native_routine_registration_skeleton()`  and adding `useDynLib("RcppParallel", .registration = TRUE)` to the `NAMESPACE` file but would then get compilation errors such as `error: invalid argument '-std=gnu++11' not allowed with 'C/ObjC'`

**Comment by eddelbuettel** [comment]
Current versions of Rcpp deal with this automagically when you run `compileAttributes()`.  It should not have a side effect on macOS.  Can you poke some more?

**Comment by jjallaire** [comment]
We actually don't use attributes in RcppParallell and also don't do useDynLib (since we manually load the library) so we need to do it manually. The issue reported by @jolars is overcome by just using a .cpp suffix with appropriate uses of `extern "C"`. Fixed here: https://github.com/RcppCore/RcppParallel/commit/d822b21a81fcb7fbe9c7e4e9dc41cc94cd043694

**Comment by kevinushey** [comment]
Looks like @jjallaire fixed this one up; feel free to open a new issue if you're still bumping into problems.
