### ISSUE TITLE
RList

### ISSUE THREAD

**Issue by mikldk** [RcppCore/RcppParallel#50]
Is it possible to use a Rcpp::List in a Worker instead of an RVector/RMatrix? If so, is there an example demonstrating it? I haven't been able to find any and is wondering if it's not possible. All entries in the List are the same type (an external pointer).

**Comment by mikldk** [comment]
The option I am considering is to use concurrent_vector from TBB instead and sequentially copy to List afterwards.

**Comment by jjallaire** [comment]
If you are going to access the external pointers directly (i.e. the R part
is just a wrapper over the pointer you want to do something else
interesting with) then you could just copy the pointers themselves to a
numeric vector and then use RVector over that.

**Comment by mikldk** [comment]
Thanks, that hack may work. 

But would an RList be possible? Or is there anything preventing that it can be done which is why it doesn't already exists? Or is it simply because it hasn't been needed yet?

**Comment by dselivanov** [comment]
It depends on what you want. If you know the structure of each `SEXP` object and can extract data/pointers **without touching R API** you can probably use `list` from threads (correct me if I'm wrong). 

The main difference is that `RMatrix/RVector` are essentially `int *` or `double *` (you can notice that there is no `RMatrix<character>`, `RVector<character>` class for), but `list` is an array of arbitrary `SEXP`, so you usually don't know what is inside and it problematic to understand it without touching R API.

Also note that when you work with lists, there is no data locality. So program could easily become memory bound.

**Comment by mikldk** [comment]
Thanks. I'll probably simply give it a go with concurrent_vector and convert it afterwards.
