### ISSUE TITLE
R related structures with tbb::mutex

### ISSUE THREAD

**Issue by mikldk** [RcppCore/RcppParallel#51]
Is it correctly understood that I can do all R related stuff if I ensure that it is encapsulated within a `tbb::mutex` with `lock()` and `unlock()`? E.g. create `Rcpp::XPtr`, assign element `i` of a `Rcpp::List` etc.

**Comment by eddelbuettel** [comment]
Yes, sounds good to me :)

**Comment by jjallaire** [comment]
Not quite. You can't ever call R from a background thread because the
garbage collector can never run anywhere but the main thread

**Comment by eddelbuettel** [comment]
Ah, I may have misunderstood the question.  

Indeed you generally cannot go off and call back into R (and/or its data structures) from any odd thread.  We are coming from R via `.Call()` in a singlethreaded context.  Then, we may do some work in parallel, and generally without R data or resources, gathers results, and return.

**Comment by mikldk** [comment]
I need to create a large number of Rcpp::XPtr from a single Rcpp function called from R. This now works when I do it with a Worker in parallel with a mutex, but what you say is that it is not safe? So I need to restructure my function and data structures so that I do not use any R structures in a Worker (except for potentially objects guaranteed to have contiguous memory like vectors via RVector/RMatrix)?

**Comment by jjallaire** [comment]
Here are the guidelines: http://rcppcore.github.io/RcppParallel/#api_restrictions

There will be a problem if R garbage collection runs while you are creating your Rcpp::XPtr objects. My guess is that Rcpp::XPtr objects allocate an SEXP, which means that garbage collection *may indeed run* depending on the state of memory at the time of the call. The fact that it "works" in your observations simply means that the R garbage collector is not running.

**Comment by mikldk** [comment]
Thanks for clarifying.
