### ISSUE TITLE
GNU extensions

### ISSUE THREAD

**Issue by JingyuHe** [RcppCore/RcppParallel#53]
Hi,

I try to create a package based on RcppParallel. I have the line below in Makevar file

`PKG_LIBS += $(shell ${R_HOME}/bin/Rscript -e "RcppParallel::RcppParallelLibs()")`

However, when I check the package as CRAN, there is a warning message

Portable Makefiles do not use GNU extensions such as +=, :=, $(shell),
$(wildcard), ifeq ... endif. See section ‘Writing portable packages’ in
the ‘Writing R Extensions’ manual.

How can I fix it? Thanks!

**Comment by eddelbuettel** [comment]
See Writing R Extensions, and some other packages, and add

```
      SystemRequirements: GNUmake
```

Or rewrite your build system (which I have done, but maybe only in packages at work):
- add a (shell) script `configure`
- in it, get the directory that RcppParallel is in
- write that value into `src/Makevars`, maybe by 'updating' a file `src/Makevars.in`.
