### ISSUE TITLE
override TBB's -fPIC flags

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/RcppParallel#57]
From BDR:

> This concerns packages
> 
> DESP JuniperKernel PythonInR RClickhouse RcppParallel nimble odbc qtutils rmumps
> 
> which are compiling code with -fPIC on a platform where all the settings in etc/Makeconf are -fpic.  (Hint: not all compilers accept -fPIC even on Linux.)
> 
> This contravenes the CRAN policy: use the settings R is built with or
> overridden in the user's Makevars.
> 
> Please correct ASAP and before Feb 1 to safely retain the package on CRAN.

TBB sets these flags according to the OS + compiler combination, e.g.

```
kevin@cdrv:~/r/pkg/RcppParallel/src [master]
$ ag -Q "PIC_KEY ="
tbb/build/windows.gcc.inc
59:PIC_KEY =

tbb/build/FreeBSD.gcc.inc
25:PIC_KEY = -fPIC

tbb/build/linux.xl.inc
27:PIC_KEY = -qpic

tbb/build/macos.clang.inc
27:PIC_KEY = -fPIC

tbb/build/android.gcc.inc
26:PIC_KEY = -fPIC

tbb/build/android.clang.inc
26:PIC_KEY = -fPIC

tbb/build/macos.gcc.inc
27:PIC_KEY = -fPIC

tbb/build/linux.gcc.inc
25:PIC_KEY = -fPIC

tbb/build/linux.clang.inc
25:PIC_KEY = -fPIC

tbb/build/macos.icc.inc
27:PIC_KEY = -fPIC

tbb/build/linux.pathcc.inc
25:PIC_KEY = -fPIC

tbb/build/linux.icc.inc
25:PIC_KEY = -fPIC

tbb/build/FreeBSD.clang.inc
25:PIC_KEY = -fPIC

tbb/build/SunOS.gcc.inc
25:PIC_KEY = -fPIC

tbb/build/SunOS.suncc.inc
25:PIC_KEY = -KPIC

tbb/build/mic.icc.inc
25:PIC_KEY = -fPIC

tbb/build/android.icc.inc
26:PIC_KEY = -fPIC

tbb/build/AIX.gcc.inc
25:PIC_KEY = -fPIC
```

so I suppose we need to patch these Makefiles and set the flag according to how R was configured / the user's Makeflags...

**Comment by eddelbuettel** [comment]
What a pain.  As if the build wasn't complicated enough.  TIA for slogging through though.
