### ISSUE TITLE
local Makevars is ignored when building tbb

### ISSUE THREAD

**Issue by sgsokol** [RcppCore/RcppParallel#69]
Trying to install from the latest daddb26 on my Linux box complains about missing `-fPIC`. Moreover, options given in ~/.R/Makevars
```
PKG_CXXFLAGS += -fPIC -O3 -mtune=native -march=native -std=c++11
```
are ignored when building tbb. Here are some examples of compiling/linking commands and corresponding error messages:
```
...
g++ -o tbb_main.o -c -MMD -DDO_ITT_NOTIFY -g -O2 -DUSE_PTHREAD -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/tbb_main.cpp
...
g++  -o libtbb.so.2 concurrent_hash_map.o concurrent_queue.o concurrent_vector.o dynamic_link.o itt_notify.o cache_aligned_allocator.o pipeline.o queuing_mutex.o queuing_rw_mutex.o reader_writer_lock.o spin_rw_mutex.o x86_rtm_rw_mutex.o spin_mutex.o critical_section.o mutex.o recursive_mutex.o condition_variable.o tbb_thread.o concurrent_monitor.o semaphore.o private_server.o rml_tbb.o tbb_misc.o tbb_misc_ex.o task.o task_group_context.o governor.o market.o arena.o scheduler.o observer_proxy.o tbb_statistics.o tbb_main.o    -ldl -lpthread -lrt -shared -Wl,-soname=libtbb.so.2 -m64  -Wl,--version-script,tbb.def
/usr/bin/ld: concurrent_queue.o: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
concurrent_queue.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
../../build/Makefile.tbb:107: recipe for target 'libtbb.so.2' failed

**Comment by kevinushey** [comment]
What version of R are you using? What is the output of:

```
R CMD config CXX11PICFLAGS
R CMD config CXX1XPICFLAGS
```

Was your version of R compiled with C++11 support?

**Comment by sgsokol** [comment]
My R is v3.5.0 (for previous R versions I had not this problem).
CXX11PICFLAGS and CXX1XPICFLAGS are not set. But I did set a general CXXPICFLAGS
```
R CMD config CXXPICFLAGS
-fPIC
```
I'll try to set CXX11PICFLAGS and CXX1XPICFLAGS and report the result.

**Comment by sgsokol** [comment]
Setting CXX11PICFLAGS and CXX1XPICFLAGS to -fPIC (as well as CXX11 and CXX1X to g++) in config.site solved the failure in linking. It remains only taking into account local Makevars options.

**Comment by kevinushey** [comment]
@sgsokol This should be fixed in the latest version of RcppParallel. Can you let me know if things work for you?

Also, I believe that the variables prefixed with `PKG_`, e.g. `PKG_CXXFLAGS`, are typically considered as 'reserved' for use by the package author; users who want to tweak their own flags should set the plain old e.g. `CXXFLAGS`. At least, that's my interpretation of https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-Makevars.

**Comment by sgsokol** [comment]
Compiler evocation remained the same for me, e.g.:
```
g++ -o concurrent_hash_map.o -c -MMD -DDO_ITT_NOTIFY -g -O2 -DUSE_PTHREAD -m64 -mrtm  -fPIC  -D__TBB_BUILD=1 -Wall   -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_hash_map.cpp
```
Following your recomendation, I have tried in ~/.R/Makevars:
```
CXXFLAGS=-O3 -mtune=native -march=native
```
but to no avail. It did not change g++ command above.
Setting CXXFLAGS in the shell before calling R did not help neither.

I can see `PKG_...` vars manipulated in src/Makevars.in but they are never passed to make compiling tbb, are they?

**Comment by kevinushey** [comment]
You might also try setting `CXX11FLAGS` and / or `CXX1XFLAGS` as well, depending on what version of R you're using and whether it comes with explicit C++11 support.

**Comment by sgsokol** [comment]
Setting CXX11FLAGS in ~/.R/Makevars did the trick, thank you (setting CXX1XFLAGS did nothing). As I already mentioned, my R version is 3.5.0. Gcc is 5.5.0 so C++11 standard is fully supported.
Thanks again.

**Comment by kevinushey** [comment]
Awesome! Glad to hear it and thanks for taking the time to test and verify.
