### ISSUE TITLE
GCC8 Issue: tbb/concurrent_hash_map.h:169:68: warning: 'void* memset

### ISSUE THREAD

**Issue by junhewk** [RcppCore/RcppParallel#70]
Hi developers of RcppParallel,

I made a package via RcppParallel for threading. The input was CharacterVector, so I relied on TBB library.
I published the package [RcppMeCab](https://cran.r-project.org/web/packages/RcppMeCab/index.html). However, the CRAN build test gave this warning:

```
* checking whether package â€˜RcppMeCabâ€™ can be installed ... [40s/14s] WARNING
Found the following significant warnings:
  /data/gannet2/ripley/R/test-gcc8/RcppParallel/include/tbb/concurrent_hash_map.h:169:68: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct tbb::interface5::internal::hash_map_base::bucket' with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
See â€˜/data/gannet/ripley/R/packages/tests-gcc8/RcppMeCab.Rcheck/00install.outâ€™ for details.
```

I didn't use the concurrent_hash_map function in my package. But the current situation is similar to this thread: [GCC 8.1 warning](https://github.com/01org/tbb/issues/54). How can I solve this problem?

**Comment by kevinushey** [comment]
I've tried working around most of these in https://github.com/RcppCore/RcppParallel/commit/daddb26e2f69156ba5f9211fcd5d5e0ee7f22a8b, but haven't yet had time to prepare a CRAN release. I'll try to double-check that everything looks good with gcc 8 and then submit to CRAN if all looks well soon.

**Comment by kevinushey** [comment]
The fixes for these should now be on CRAN (circa 2018-07-19)

**Comment by msuchard** [comment]
Unfortunately, I am still running up against the following on CRAN incoming auto-checks:

```
Flavor: r-devel-linux-x86_64-debian-gcc
Check: whether package can be installed, Result: WARNING
 Found the following significant warnings:
   /home/hornik/lib/R/Library/3.6/x86_64-linux-gnu/RcppParallel/include/tbb/concurrent_vector.h:88:20: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct tbb::internal::padded<tbb::interface6::internal::ets_element<float>, 128>'; use assignment or value-initialization instead [-Wclass-memaccess]
```

Any advice on a local (within my package `Cyclops`) workaround?

**Comment by kevinushey** [comment]
Sorry, I don't think there's any package-local workaround that can be attempted here. I would just advise CRAN that this is an issue in RcppParallel + TBB and that the warning is otherwise safe to ignore + shouldn't block acceptance of your package.
