### ISSUE TITLE
How to get the number of available threads in the cpp file?

### ISSUE THREAD

**Issue by badbye** [RcppCore/RcppParallel#74]
My algorithm needs to generate random numbers in each loop. I want to create **multiples random generators** for each thread.
However, I did not find the API to get the number of available threads.

**Comment by jjallaire** [comment]
If you are using C++11 you can use `std::thread::hardware_concurrency()`

**Comment by badbye** [comment]
After running `setThreadOptions(2)`, `std::thread::hardware_concurrency()` still gives the default thread numbers(it is 4 on my laptop).

**Comment by jjallaire** [comment]
If you've called setThreadOptions you get retrieve that value as an environment variable (`RCPP_PARALLEL_NUM_THREADS`)

**Comment by badbye** [comment]
That is what I want, thanks.

**Comment by eddelbuettel** [comment]
For completeness, there is also an R level interface to the same variables generally respected by OpenMP, (Intel) MKL, (Intel) TBB (and hence RcppParallel) and others:

```r
R> library(RhpcBLASctl)
R> get_num_procs()
[1] 12
R> omp_get_max_threads()
[1] 12
R> get_num_cores()
[1] 6
R>
```

which is correct given my i7-8700k.  You could dig into the package if you needed it at the C(++)-level.

Now, as for RNGs, better be careful and pick a stream-aware parallel RNGs such as [sitmo](https://cloud.r-project.org/web/packages/sitmo/index.html) or [dqrng](https://cran.r-project.org/web/packages/dqrng/index.html).
