### ISSUE TITLE
Rvector is not safe enough?

### ISSUE THREAD

**Issue by badbye** [RcppCore/RcppParallel#75]
Hi, I am testing a small example to count numbers. The result is not always correct.

Here is my code:
```
struct Runner : public Worker
{
  RVector<int> v;
  Runner(RVector<int> v): v(v){}
  void operator()(std::size_t begin, std::size_t end) {
    for (std::size_t i=begin; i<end; i++){
      v[0] ++;
    }
  }
};
                      

// [[Rcpp::export]]
int test_rvector(int s){
  IntegerVector x(s);
  RVector<int> v(x);
  Runner run(v);
  parallelFor(0, s, run);
  return v[0];
}
```

As `RVector` is thread safe, the value of `v[0]` should be the value of `s`. However, it is not. My question could be stupid, but it really wastes me a lot of time to figure it out. Am I missing something? 
```
test_rvector(1000)  # not always return 1000
```

**Comment by eddelbuettel** [comment]
Parallel computing is a little more complicated.  You are, if I understand your example correctly, assuming that multiple threads would work on one shared data structure without contention.  But this is not this easy -- you need some coordination.

**Comment by badbye** [comment]
@eddelbuettel

**Comment by badbye** [comment]
@eddelbuettel   I am a freshman on parallel computing. If using OpenMP, I know I should lock the variable before I do

**Comment by eddelbuettel** [comment]
You just can't assume lockfree write access.  See [eg here on `fetch_and_increment`](https://rcppcore.github.io/RcppParallel/tbb.html) as well as in the TBB docs. 

I just did a trivial mod to your program to have it actually 'touch' each element of the output vector, turning it from 0 to 1.  That works fine.

```r
R> sum(test_rvector(1000))
[1] 1000
R> sum(test_rvector(1e6))
[1] 1000000
R> 
```

But the key here is _that each thread works on a different segment of the vector_ so we have no contention.  Your code just assumed _everybody_ could access `v[0]` without lossage.  I don't think you can assume that, and you result indicated that you cannot.
