### ISSUE TITLE
RcppParallel Download Error

### ISSUE THREAD

**Issue by bgynr** [RcppCore/RcppParallel#76]
install.packages("RcppParallel") 
..... 
...... 
.... 
.... 
.....
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Warning in fun(libname, pkgname) : TBB library  not found.
Warning in fun(libname, pkgname) : TBB malloc library  not found.
Error : .onLoad failed in loadNamespace() for 'RcppParallel', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/packages/r-3.3.1/lib64/R/library/RcppParallel/libs/RcppParallel.so':
  /packages/r-3.3.1/lib64/R/library/RcppParallel/libs/RcppParallel.so: undefined symbol: _ZN3tbb19task_scheduler_init9terminateEv
Error: loading failed
Execution halted
ERROR: loading failed
* removing â/packages/r-3.3.1/lib64/R/library/RcppParallelâ

The downloaded source packages are in
        â/tmp/Rtmp4UfvVO/downloaded_packagesâ
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("RcppParallel") :
  installation of package âRcppParallelâ had non-zero exit status

**Comment by eddelbuettel** [comment]
What OS?  Linux? If so, which distro?

What did configure output earlier? When we see 

```
Warning in fun(libname, pkgname) : TBB library not found.
Warning in fun(libname, pkgname) : TBB malloc library not found.
```

it is "too late" but indicative of another (earlier) failure.
