### ISSUE TITLE
Remove link to BH

### ISSUE THREAD

**Issue by ChrisMuir** [RcppCore/RcppParallel#80]
Currently, `BH` is listed in the `LinkingTo` field of the `DESCRIPTION` file. As far as I can tell, it's not necessary.

It looks like `BH` was added in [this](https://github.com/RcppCore/RcppParallel/pull/20) PR (specifically, in [this](https://github.com/RcppCore/RcppParallel/pull/20/commits/a33642053e49e16afb99d49526cdcaafb463dcfd) commit), but it seems that `inst/include/boost` has since been removed.

I'd be happy to submit a PR for this, but wanted to open an issue first, since there may be some other reason(s) to keep a link to `BH` that I'm just not seeing. If that's not the case, let me know and I'll submit a PR.

**Comment by ChrisMuir** [comment]
Forgot to mention....I cloned the repo, removed the link to `BH`, and am able to build the package and all tests pass locally. This is on a Mac with R 3.5.0.

**Comment by kevinushey** [comment]
Thanks! I think that's a relic from when we previously were including Boost.SIMD in RcppParallel (which later became its own package, [https://github.com/RcppCore/RcppNT2](RcppNT2). Unfortunately that package never really gained much traction.

I'll remove it -- thanks for spotting.
