### ISSUE TITLE
fatal error on installation (debian 9.6)

### ISSUE THREAD

**Issue by mcooganj** [RcppCore/RcppParallel#84]
hi -- this is not necessarily a bug, but i wanted to report as it's unusual.  I've not seen my (fairly small) .Rprofile setup cause these problems before. 

I'm running R 3.5.1 on Debian 9.6 and had a fatal error on an attempt to install.  The output error was as below: 

* preparing to configure package 'RcppParallel' ...
* finished configure for package 'RcppParallel'
** libs
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/mck/R/rpax/BH/include"    -fpic  -g -O2 -fdebug-prefix-map=/home/jranke/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.cpp -o init.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/mck/R/rpax/BH/include"    -fpic  -g -O2 -fdebug-prefix-map=/home/jranke/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c options.cpp -o options.o
options.cpp:2:26: fatal error: RcppParallel.h: No such file or directory
 #include <RcppParallel.h>

I was able to fix it by opening using $R --vanilla  and installing from CRAN ... but installation of the github version (via devtools::install_github) thereafter also gave the same fatal error. 

Perhaps it's a clash with devtools? 

> devtools::install_github("RcppCore/RcppParallel")
Downloading GitHub repo RcppCore/RcppParallel@master
✔  checking for file ‘/tmp/Rtmp026uhh/remotes9178f4fd2/RcppCore-RcppParallel-0ef5400/DESCRIPTION’ (381ms)
─  preparing ‘RcppParallel’: (2.3s)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts (580ms)
─  checking for empty or unneeded directories (1.1s)
─  building ‘RcppParallel_4.4.1-1.tar.gz’

Installing package into ‘/home/mck/R/rpax’
(as ‘lib’ is unspecified)
Loading required package: xts
Loading required package: zoo
Loading required package: stats

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

* installing *source* package ‘RcppParallel’ ...
Loading required package: xts
Loading required package: zoo
Loading required package: stats

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

** preparing to configure package 'RcppParallel' ...
** finished configure for package 'RcppParallel'
** libs
g++  -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/home/jranke/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.cpp -o init.o
g++  -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/home/jranke/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c options.cpp -o options.o
options.cpp:2:26: fatal error: RcppParallel.h: No such file or directory
 #include <RcppParallel.h>
                          ^
compilation terminated.
/usr/lib/R/etc/Makeconf:168: recipe for target 'options.o' failed
make: *** [options.o] Error 1
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/home/mck/R/rpax/RcppParallel’
* restoring previous ‘/home/mck/R/rpax/RcppParallel’
Error in i.p(...) :
  (converted from warning) installation of package ‘/tmp/Rtmp026uhh/file983b9c54/RcppParallel_4.4.1-1.tar.gz’ had non-zero exit status

**Comment by eddelbuettel** [comment]
> Perhaps it's a clash with devtools?

Possibly.  The package installs cleanly [1] on every system tested at CRAN: https://cloud.r-project.org/web/checks/check_results_RcppParallel.html

[1] Apart from the standard nags about directory size, and GNU make use.

**Comment by mcooganj** [comment]
To be clear — installation from cran using an R —vanilla startup worked for
me.

But installation from github fails. And installation from CRAN when i had
devtools loaded caused the same error.

Not sure of this is useful information. Feel free to close the issue if you
like.

**Comment by eddelbuettel** [comment]
I am not the maintainer here but for the packages I maintainer I'd close this. You should have no expectation of _guaranteed immediate installability_ when hitting "random" GH checkouts.

If you want a trusted and installable version, use the most current CRAN release.  We all work hard to make CRAN work that way.  If you go another route you may get to pick up the pieces.

**Comment by kevinushey** [comment]
RcppParallel adds its own include path during compilation here:

https://github.com/RcppCore/RcppParallel/blob/master/src/Makevars.in#L1

My guess is that your `.Rprofile` is overriding `PKG_CPPFLAGS` -- you should either append or amend the existing variables, or better yet just set `CXXFLAGS` or similar.

I'm going to close this because I don't think there's anything actionable for us here.
