### ISSUE TITLE
build and expose tbb static library

### ISSUE THREAD

**Issue by mikejiang** [RcppCore/RcppParallel#88]
Is it possible make static version (`libtbb.a`) available for C++ code (non-Rcpp) in other R packages (e.g. https://github.com/RGLab/flowWorkspace/issues/268) so that the same bundling and building efforts for tbb can be avoided? Currently only dynamic shared library (`libtbb.so`) is available but I guess it is not recommended to be used to link dynamically against the other package (see https://github.com/eddelbuettel/rprotobuf/issues/1#issuecomment-66241724) due to the potential runtime conflicts among multiple versions of libraries (e.g. tbb installed system-wise)

I saw https://github.com/jjallaire/TBB, which doesn't seem to be maintained recently, nor is it submitted to CRAN.

**Comment by jjallaire** [comment]
You can link to all of TBB via RcppParallel (it's dynamically loaded when the package is loaded and RcppParallel.h gives you access to all of the headers you need).

**Comment by mikejiang** [comment]
Do you mean link to `RcppParallel.so` ?or `libtbb.so` through
```r
> RcppParallel:::tbbLibPath()
[1] "/home/wjiang2/R/x86_64-pc-linux-gnu-library/3.6/RcppParallel/lib/libtbb.so.2"
```
None of the following APIs return the lib flags I need
```r
> RcppParallel:::tbbLdFlags()
[1] ""
> RcppParallel::LdFlags()
> RcppParallel::RcppParallelLibs()
> packageVersion("RcppParallel")
[1] ‘4.4.2’
> Sys.info()['sysname']
sysname 
"Linux" 
```
I can do it manually on my own, but it would be nice to have these functions work as expected.

**Comment by jjallaire** [comment]
You don't need to link to TBB, it's all done with headers. Just include RcppParallel.h and you get all of tbb/tbb.h

**Comment by eddelbuettel** [comment]
@mikejiang In general, you can't. 

If it was as easy as referencing shared libraries in other installed packages, you would see _a lot_ more use of that across packages.  In short, you can't, and so you don't.  

What @jjallaire was referring is that when RcppParallel in loaded in an R session the symbols from TBB should resolve.  (Similar to how, say, various packages can hit LAPACK entry points because R loads LAPACK.)  But that indirect use is generally all you get.

**Comment by mikejiang** [comment]
@jjallaire , my package failed `R CMD INSTALL` without linking to tbb
```bash
Error: package or namespace load failed for ‘flowWorkspace’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object 'flowWorkspace.so':
x86_64-pc-linux-gnu-library/3.6/flowWorkspace/libs/flowWorkspace.so: undefined symbol: _ZTIN3tbb4taskE
```
@eddelbuettel , I managed to link and store tbb runtime path through `rpath`, i.e.
```
-Wl,-rpath=/home/wjiang2/R/x86_64-pc-linux-gnu-library/3.6/RcppParallel/lib -L/home/wjiang2/R/x86_64-pc-linux-gnu-library/3.6/RcppParallel/lib
```
Things seem to work. But I guess there is something I might be missing here and need your help to explain a bit more on why this is not good practice.

**Comment by eddelbuettel** [comment]
Your [`DESCRIPTION`](https://github.com/RGLab/flowWorkspace/blob/trunk/DESCRIPTION) does not include RcppParallel.  

Try adding it, with an explicit import of a symbol just as we do for Rcpp.

**Comment by mikejiang** [comment]
import `RcppParallelLibs` from `RcppParallel` works!
Thanks a lot!

**Comment by eddelbuettel** [comment]
Good to know it is solved.  Out of curiousity, and while I am totally unfamiliar with your package, where did the depends on RcppParallel come from, ie which other package (that you depend on here) accesses it?

**Comment by eddelbuettel** [comment]
Thanks.  But if it is in another branch how could it throw a spanner into your main build?

**Comment by mikejiang** [comment]
@jjallaire , I am reopening this request due to the strong opinions against cross-package shared lib , https://github.com/grimbough/Rhdf5lib/issues/13#issuecomment-451678937

**Comment by kevinushey** [comment]
Given the reservations around static linking for TBB I'm going to close this. I don't think we should try to switch anything here unless it solves a concrete problem users are having, and I doubt there are many instances where there could be multiple versions of TBB loaded / used by different packages.
