### ISSUE TITLE
failed to install RcppParallel on the Ubuntu 18.04 for the RcppParallel.h file cannot be found 

### ISSUE THREAD

**Issue by xning** [RcppCore/RcppParallel#91]
OS: Ubuntu 18.04.1 LTS
kernel: 4.15.0-44-generic
R: 3.5.2

Only installed r-base-core and r-base-dev from the cloud.r-project.org apt repo. After that, installed ggplot2 package successfully. While installing RcppParallel ，I saw following msg:

foundpkgs: RcppParallel, /tmp/RtmphvklZD/downloaded_packages/RcppParallel_4.4.2.tar.gz
files: /tmp/RtmphvklZD/downloaded_packages/RcppParallel_4.4.2.tar.gz
* installing *source* package ‘RcppParallel’ ...
** package ‘RcppParallel’ successfully unpacked and MD5 sums checked
** preparing to configure package 'RcppParallel' ...
** finished configure for package 'RcppParallel'
** libs
g++  -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-i39faS/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.cpp -o init.o
g++  -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-i39faS/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c options.cpp -o options.o
options.cpp:2:10: fatal error: RcppParallel.h: No such file or directory
 #include <RcppParallel.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
/usr/lib/R/etc/Makeconf:171: recipe for target 'options.o' failed
make: *** [options.o] Error 1
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/home/nerd/.R/lib/RcppParallel’

The downloaded source packages are in
	‘/tmp/RtmphvklZD/downloaded_packages’
Warning message:
In install.packages(pkgs = c("RcppParallel"), dependencies = TRUE,  :
  installation of package ‘RcppParallel’ had non-zero exit status
>

**Comment by eddelbuettel** [comment]
Also, to bypass the issue, you can install a binary version from here:  https://launchpad.net/~marutter/+archive/ubuntu/c2d4u3.5?field.series_filter=bionic.

**Comment by xning** [comment]
@eddelbuettel 

Thanks a lot. Installed the package successfully after removing the the .Rprofile  file.

**Comment by bbucior** [comment]
Adding a note about another potential workaround. I ran into a similar issue but was successful in installing a [download from CRAN](https://cran.r-project.org/web/packages/RcppParallel/index.html) via:

`R CMD INSTALL --use-vanilla RcppParallel_5.1.5.tar.gz`

Something in my R installation was not running the package's configure step (so `PKG_CPPFLAGS` never got defined). Using the workaround, the installation log now reports finding src/Makevars.in:

```
** package ‘RcppParallel’ successfully unpacked and MD5 sums checked
** preparing to configure package 'RcppParallel' ...
*** configured file: 'src/Makevars.in' => 'src/Makevars'
** finished configure for package 'RcppParallel'
```
