### ISSUE TITLE
FreeBSD installation error

### ISSUE THREAD

**Issue by cainesap** [RcppCore/RcppParallel#92]
Hello,
Thank you for maintaining this package. I've run into a problem trying to install on FreeBSD, with an error message as follows --
```
* installing *source* package 'RcppParallel' ...
** package 'RcppParallel' successfully unpacked and MD5 sums checked
** preparing to configure package 'RcppParallel' ...
*** executing 'R CMD config'
*** configured file: 'src/Makevars.in' => 'src/Makevars'
Error in configure_platform(type = type) : 
  unrecognized platform 'FreeBSD'
Calls: configure_auto -> configure_platform
Execution halted
ERROR: configuration failed for package 'RcppParallel'
```
Please could you let me know if there's a workaround?
thank you, Andrew

**Comment by cainesap** [comment]
Update, sorry should have tried this before posting: I stepped back to 4.4.1 and it installs ok.

**Comment by kevinushey** [comment]
As a workaround, you can try setting the R option:

    options(configure.platform = FALSE)

before package installation, but I'm not sure what the most natural place to set this would be. (This is ultimately an issue that will need to be fixed in RcppParallel; I'll try to take a look next week)
