### ISSUE TITLE
License incompatibility with TBB

### ISSUE THREAD

**Issue by wds15** [RcppCore/RcppParallel#93]
The Intel TBB is licencsed under the Apache 2.0 licence. According to the FOSS, this license is only compatible with GPL-3 while it is not compatible with earlier versions of the GPL. Please refer to [the homepage from the GNU project](https://www.gnu.org/licenses/license-list.en.html#apache2) for their view on the Apache 2.0. There they explicitly list that the GPL-2 is incompatible with the Apache 2.0 license. Currently, RcppParallel is released under the GPL-2 and an update to GPL-3 should be considered, I think.

**Comment by eddelbuettel** [comment]
Thanks, probably something we should do.

**Comment by wds15** [comment]
Sure... NP. I hope that's an easy thing to do.

**Comment by kevinushey** [comment]
Sorry for the delay; I've finally made this change with https://github.com/RcppCore/RcppParallel/commit/577c920abf766fbfeaa840c11b6a93afce6f923a.
